import crypto from 'node:crypto';
import { execSync } from 'node:child_process';
import path from 'node:path';
import { createClient } from '@supabase/supabase-js';
import { isLoopbackUrl, parseSupabaseCliEnv } from '../local-development/localEnvironmentFile';

const root = path.resolve(__dirname, '../../../..');
const prefix = `approval-gate-${Date.now().toString(36)}`;
const sql = (query: string) => execSync(`docker exec supabase_db_capstone-impact-platform psql -U postgres -d postgres -At -v ON_ERROR_STOP=1 -c "${query.replace(/"/g, '\\"')}"`, { cwd: root, encoding: 'utf8' }).trim();
const one = <T>(query: string): T => JSON.parse(sql(`SELECT row_to_json(t) FROM (${query}) t`));
const count = (query: string) => Number(sql(query));
function assert(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message); }
const test = async (number: number, name: string, body: () => Promise<void>) => { console.log(`--- Test ${number}: ${name} ---`); await body(); console.log(`PASS: Test ${number} - ${name}.`); };

async function main() {
  const raw = execSync(`"${path.join(root, 'node_modules/.bin/supabase')}" status --workdir "${path.join(root, 'infra')}" -o env`, { cwd: root, encoding: 'utf8' });
  const env = parseSupabaseCliEnv(raw);
  assert(env.API_URL && env.SERVICE_ROLE_KEY && env.ANON_KEY && isLoopbackUrl(env.API_URL), 'Local loopback Supabase is required.');
  const service = createClient(env.API_URL!, env.SERVICE_ROLE_KEY!, { auth: { autoRefreshToken: false, persistSession: false } });
  const anon = createClient(env.API_URL!, env.ANON_KEY!, { auth: { autoRefreshToken: false, persistSession: false } });
  const ids = one<{ program: string; discipline: string; industry: string; admin: string; reviewer: string; editor: string }>("SELECT (SELECT id::text FROM public.programs LIMIT 1) program,(SELECT id::text FROM public.disciplines LIMIT 1) discipline,(SELECT id::text FROM public.industry_categories LIMIT 1) industry,(SELECT au.id::text FROM public.admin_users au JOIN public.user_roles ur ON ur.user_id=au.id WHERE ur.role='admin' LIMIT 1) admin,(SELECT au.id::text FROM public.admin_users au JOIN public.user_roles ur ON ur.user_id=au.id WHERE ur.role='reviewer' LIMIT 1) reviewer,(SELECT au.id::text FROM public.admin_users au JOIN public.user_roles ur ON ur.user_id=au.id WHERE ur.role='editor' LIMIT 1) editor");
  const project = (name: string, status: string) => {
    const publicId = `${prefix}-${name}`;
    sql(`INSERT INTO public.projects(public_id,title,summary,background,solution,year,program_id,program_name,discipline,industry,status) VALUES ('${publicId}','Before','Before','Background','Solution',2026,'${ids.program}'::uuid,'Program','Discipline','Industry','${status}')`);
    return publicId;
  };
  const snapshot = (publicId: string) => one<Record<string, unknown>>(`SELECT p.title,p.summary,p.background,p.solution,p.year,p.program_id::text,p.status,p.updated_at::text,(SELECT json_agg(discipline_id::text ORDER BY discipline_id) FROM public.project_disciplines WHERE project_id=p.id) disciplines,(SELECT json_agg(industry_category_id::text ORDER BY industry_category_id) FROM public.project_industry_categories WHERE project_id=p.id) industries,(SELECT count(*) FROM public.approval_records WHERE project_id=p.id) audits FROM public.projects p WHERE public_id='${publicId}'`);
  const args = (publicId: string, title: string, updatedAt: string) => ({ p_public_id: publicId, p_title: title, p_summary: `${title} summary`, p_background: `${title} background`, p_solution: `${title} solution`, p_year: 2027, p_program_id: ids.program, p_discipline_ids: [ids.discipline], p_industry_category_ids: [ids.industry], p_expected_updated_at: updatedAt });
  const metadata = async (publicId: string, title: string) => { const row = snapshot(publicId); return service.rpc('update_project_metadata', args(publicId, title, String(row.updated_at))); };
  const review = (publicId: string, adminId = ids.admin, comments = 'runtime request changes') => service.rpc('perform_project_review_action', { p_public_id: publicId, p_action: 'request_changes', p_comments: comments, p_admin_id: adminId });
  const token = () => crypto.randomBytes(32).toString('hex');
  const generate = async (publicId: string) => { const hash = token(); const result = await service.rpc('generate_participant_preview', { p_public_id: publicId, p_admin_id: ids.admin, p_token_hash: hash, p_expires_in_seconds: 3600, p_private_bucket: 'project-drafts-private' }); assert(!result.error && result.data?.resultCode === 'SUCCESS', 'Preview generation failed'); return { hash, previewId: String(result.data.previewId) }; };
  const confirm = (hash: string) => service.rpc('confirm_participant_preview', { p_token_hash: hash });
  const correction = (hash: string) => service.rpc('request_participant_preview_correction', { p_token_hash: hash, p_comment: 'Please correct this preview.' });
  const readiness = (publicId: string) => service.rpc('get_project_publication_readiness', { p_public_id: publicId, p_admin_id: ids.admin, p_private_bucket: 'project-drafts-private' });

  try {
    await test(1, 'Draft metadata edit persists scalars, taxonomies, and draft status', async () => { const id = project('draft', 'draft'); const result = await metadata(id, 'Draft changed'); assert(!result.error && result.data?.resultCode === 'SUCCESS', 'Draft metadata save failed'); const after = snapshot(id); assert(after.title === 'Draft changed' && after.status === 'draft' && Array.isArray(after.disciplines) && Array.isArray(after.industries), 'Draft mutation did not persist correctly'); });
    await test(2, 'changes_requested metadata edit preserves state', async () => { const id = project('changes', 'changes_requested'); const result = await metadata(id, 'Changes changed'); assert(!result.error && result.data?.resultCode === 'SUCCESS' && snapshot(id).status === 'changes_requested', 'changes_requested mutation failed'); });
    await test(3, 'Approved direct metadata edit returns APPROVAL_REOPEN_REQUIRED', async () => { const id = project('approved-gate', 'approved'); const result = await metadata(id, 'Rejected'); assert(!result.error && result.data?.resultCode === 'APPROVAL_REOPEN_REQUIRED', 'Approved edit was not rejected'); });
    await test(4, 'Approved rejection is mutation-free', async () => { const id = project('approved-clean', 'approved'); const before = snapshot(id); await metadata(id, 'Rejected'); assert(JSON.stringify(snapshot(id)) === JSON.stringify(before), 'Approved rejection mutated project state'); });
    await test(5, 'Approved project without preview reopens through Request changes', async () => { const id = project('reopen', 'approved'); const result = await review(id); assert(!result.error && result.data?.status === 'changes_requested' && snapshot(id).status === 'changes_requested', 'Approved project did not reopen'); });
    await test(6, 'Reopen creates exactly one correctly attributed audit record', async () => { const id = project('audit', 'approved'); const result = await review(id, ids.reviewer, '  bounded comment  '); assert(!result.error, 'Review failed'); const audit = one<{ n: number; action: string; from: string; to: string; comment: string }>(`SELECT count(*)::int n,max(action_taken) action,max(from_status) "from",max(to_status) "to",max(comments) comment FROM public.approval_records ar JOIN public.projects p ON p.id=ar.project_id WHERE p.public_id='${id}'`); assert(audit.n === 1 && audit.action === 'request_changes' && audit.from === 'approved' && audit.to === 'changes_requested' && audit.comment === 'bounded comment', 'Audit record was incorrect'); });
    await test(7, 'Active Preview A is revoked atomically when reopening', async () => { const id = project('preview-revoke', 'approved'); const a = await generate(id); const result = await review(id, ids.reviewer); const row = one<{ status: string; revoked_by: string; has_snapshot: boolean }>(`SELECT status,revoked_by::text, snapshot IS NOT NULL has_snapshot FROM public.participant_previews WHERE id='${a.previewId}'`); assert(!result.error && result.data?.status === 'changes_requested' && row.status === 'revoked' && row.revoked_by === ids.reviewer && row.has_snapshot, 'Preview A was not safely revoked'); });
    await test(8, 'Revoked Preview A token cannot resolve, confirm, or request correction', async () => { const id = project('token', 'approved'); const a = await generate(id); await review(id); const [resolved, confirmed, corrected] = await Promise.all([service.rpc('resolve_participant_preview', { p_token_hash: a.hash }), service.rpc('confirm_participant_preview', { p_token_hash: a.hash }), service.rpc('request_participant_preview_correction', { p_token_hash: a.hash, p_comment: 'late request' })]); assert(resolved.data?.resultCode === 'NOT_FOUND' && confirmed.data?.resultCode === 'NOT_FOUND' && corrected.data?.resultCode === 'NOT_FOUND', 'Revoked token remained usable'); });
    await test(9, 'Confirmed Preview A history survives reopen', async () => { const id = project('confirmed-history', 'approved'); const a = await generate(id); const confirmed = await confirm(a.hash); assert(!confirmed.error && confirmed.data?.resultCode === 'SUCCESS', 'Preview A confirmation failed'); const before = one<{ id: string; confirmed_at: string; snapshot: unknown }>(`SELECT c.id::text,c.confirmed_at::text,pp.snapshot FROM public.participant_preview_confirmations c JOIN public.participant_previews pp ON pp.id=c.participant_preview_id WHERE pp.id='${a.previewId}'`); await review(id); const after = one<{ id: string; confirmed_at: string; snapshot: unknown; status: string }>(`SELECT c.id::text,c.confirmed_at::text,pp.snapshot,pp.status FROM public.participant_preview_confirmations c JOIN public.participant_previews pp ON pp.id=c.participant_preview_id WHERE pp.id='${a.previewId}'`); assert(after.status === 'revoked' && after.id === before.id && after.confirmed_at === before.confirmed_at && JSON.stringify(after.snapshot) === JSON.stringify(before.snapshot), 'Confirmed Preview A history changed during reopen'); });
    await test(10, 'Historical Preview A confirmation cannot authorize edited state', async () => { const id = project('historical-readiness', 'approved'); const a = await generate(id); await confirm(a.hash); await review(id); const saved = await metadata(id, 'Edited after reopen'); assert(!saved.error && saved.data?.resultCode === 'SUCCESS', 'Post-reopen metadata edit failed'); const approved = await service.rpc('perform_project_review_action', { p_public_id: id, p_action: 'approve', p_comments: 'reapprove', p_admin_id: ids.admin }); assert(!approved.error && approved.data?.status === 'approved', 'Reapproval failed'); const ready = await readiness(id); assert(!ready.error && ready.data?.resultCode !== 'READY', 'Historical revoked confirmation restored readiness'); });
    await test(11, 'Fresh Preview B begins unconfirmed and not ready', async () => { const id = project('fresh-b', 'approved'); const a = await generate(id); await confirm(a.hash); await review(id); await metadata(id, 'Changed'); await service.rpc('perform_project_review_action', { p_public_id: id, p_action: 'approve', p_comments: 'reapprove', p_admin_id: ids.admin }); const b = await generate(id); const responses = count(`SELECT count(*) FROM public.participant_preview_confirmations WHERE participant_preview_id='${b.previewId}'`); const ready = await readiness(id); assert(a.previewId !== b.previewId && responses === 0 && ready.data?.resultCode !== 'READY', 'Fresh Preview B was not independently unconfirmed'); });
    await test(12, 'Confirming exact Preview B restores READY', async () => { const id = project('confirm-b', 'approved'); const a = await generate(id); await confirm(a.hash); await review(id); await metadata(id, 'Changed'); await service.rpc('perform_project_review_action', { p_public_id: id, p_action: 'approve', p_comments: 'reapprove', p_admin_id: ids.admin }); const b = await generate(id); const confirmed = await confirm(b.hash); const ready = await readiness(id); assert(confirmed.data?.resultCode === 'SUCCESS' && ready.data?.resultCode === 'READY' && count(`SELECT count(*) FROM public.participant_preview_confirmations WHERE participant_preview_id IN ('${a.previewId}','${b.previewId}')`) === 2, 'Fresh Preview B did not establish readiness'); });
    await test(13, 'Open correction blocks generic Request changes without mutation', async () => { const id = project('open-correction', 'approved'); const a = await generate(id); const requested = await correction(a.hash); assert(!requested.error && requested.data?.resultCode === 'SUCCESS', 'Correction request failed'); const before = one<{ status: string; audit: number }>(`SELECT p.status,(SELECT count(*)::int FROM public.approval_records WHERE project_id=p.id) audit FROM public.projects p WHERE public_id='${id}'`); const result = await review(id); const after = one<{ status: string; audit: number; correction: string }>(`SELECT p.status,(SELECT count(*)::int FROM public.approval_records WHERE project_id=p.id) audit,(SELECT status FROM public.participant_preview_correction_requests WHERE participant_preview_id='${a.previewId}') correction FROM public.projects p WHERE public_id='${id}'`); assert(!result.error && result.data?.resultCode === 'CORRECTION_RESOLUTION_REQUIRED' && after.status === before.status && after.audit === before.audit && after.correction === 'open', 'Generic reopen bypassed open correction'); });
    await test(14, 'in_progress correction remains authoritative', async () => { const id = project('in-progress', 'approved'); const a = await generate(id); await correction(a.hash); const started = await service.rpc('start_participant_preview_correction_resolution', { p_public_id: id, p_admin_id: ids.admin }); assert(!started.error && started.data?.resultCode === 'SUCCESS', 'Resolution start failed'); const before = one<{ started: string; audit: number }>(`SELECT resolution_started_at::text started,(SELECT count(*)::int FROM public.approval_records ar JOIN public.projects p ON p.id=ar.project_id WHERE p.public_id='${id}') audit FROM public.participant_preview_correction_requests WHERE participant_preview_id='${a.previewId}'`); const generic = await review(id); const after = one<{ status: string; started: string; audit: number }>(`SELECT r.status,r.resolution_started_at::text started,(SELECT count(*)::int FROM public.approval_records ar JOIN public.projects p ON p.id=ar.project_id WHERE p.public_id='${id}') audit FROM public.participant_preview_correction_requests r WHERE participant_preview_id='${a.previewId}'`); assert(Boolean(generic.error) && after.status === 'in_progress' && after.started === before.started && after.audit === before.audit, 'Generic action corrupted in-progress correction'); });
    await test(15, 'Dedicated correction-resolution workflow preserves its lifecycle', async () => { const id = project('resolution', 'approved'); const a = await generate(id); await correction(a.hash); const result = await service.rpc('start_participant_preview_correction_resolution', { p_public_id: id, p_admin_id: ids.admin }); const row = one<{ status: string; started_by: string; preview: string; project: string }>(`SELECT r.status,r.resolution_started_by::text started_by,pp.status preview,p.status project FROM public.participant_preview_correction_requests r JOIN public.participant_previews pp ON pp.id=r.participant_preview_id JOIN public.projects p ON p.id=pp.project_id WHERE pp.id='${a.previewId}'`); assert(!result.error && result.data?.resultCode === 'SUCCESS' && row.status === 'in_progress' && row.started_by === ids.admin && row.preview === 'revoked' && row.project === 'changes_requested', 'Correction-resolution lifecycle regressed'); });
    await test(16, 'Contradictory active previews fail closed without mutation', async () => { const id = project('ambiguous', 'approved'); const a = await generate(id); const projectId = sql(`SELECT id::text FROM public.projects WHERE public_id='${id}'`); sql('DROP INDEX public.uq_participant_previews_one_active_per_project'); sql(`INSERT INTO public.participant_previews(project_id,token_hash,snapshot,media_snapshot,status,created_by,expires_at) VALUES ('${projectId}'::uuid,'${token()}'::text,'{}'::jsonb,'[]'::jsonb,'active','${ids.admin}'::uuid,now()+interval '1 hour')`); const before = count(`SELECT count(*) FROM public.approval_records ar JOIN public.projects p ON p.id=ar.project_id WHERE p.public_id='${id}'`); const result = await review(id); const active = count(`SELECT count(*) FROM public.participant_previews pp JOIN public.projects p ON p.id=pp.project_id WHERE p.public_id='${id}' AND pp.status='active'`); assert(!result.error && result.data?.resultCode === 'AMBIGUOUS_ACTIVE_PREVIEW' && snapshot(id).status === 'approved' && active === 2 && count(`SELECT count(*) FROM public.approval_records ar JOIN public.projects p ON p.id=ar.project_id WHERE p.public_id='${id}'`) === before, 'Ambiguous previews were not failed closed'); void a; });
    await test(19, 'Editor has edit authority but cannot review', async () => { const id = project('editor', 'submitted'); const roles = sql(`SELECT string_agg(role,',') FROM public.user_roles WHERE user_id='${ids.editor}'`); const before = snapshot(id); const result = await review(id, ids.editor); assert(roles.includes('editor') && !roles.includes('reviewer') && Boolean(result.error) && JSON.stringify(snapshot(id)) === JSON.stringify(before), 'Editor role boundary failed'); });
    await test(20, 'Reviewer has review authority but not edit authority', async () => { const id = project('reviewer', 'submitted'); const roles = sql(`SELECT string_agg(role,',') FROM public.user_roles WHERE user_id='${ids.reviewer}'`); const result = await review(id, ids.reviewer); assert(roles.includes('reviewer') && !roles.includes('editor') && !result.error && result.data?.status === 'changes_requested', 'Reviewer role boundary failed'); });
    await test(21, 'Admin retains edit and review authority', async () => { const mutable = project('admin-edit', 'draft'); const reviewed = project('admin-review', 'submitted'); const roles = sql(`SELECT string_agg(role,',') FROM public.user_roles WHERE user_id='${ids.admin}'`); const saved = await metadata(mutable, 'Admin changed'); const result = await review(reviewed, ids.admin); assert(roles.includes('admin') && saved.data?.resultCode === 'SUCCESS' && result.data?.status === 'changes_requested', 'Admin combined authority failed'); });
    await test(24, 'Confirmation and reopen serialize safely', async () => { const id = project('confirm-race', 'approved'); const a = await generate(id); const [confirmed, reopened] = await Promise.all([confirm(a.hash), review(id)]); const row = one<{ status: string; confirmations: number; project: string }>(`SELECT pp.status,(SELECT count(*)::int FROM public.participant_preview_confirmations WHERE participant_preview_id=pp.id) confirmations,p.status project FROM public.participant_previews pp JOIN public.projects p ON p.id=pp.project_id WHERE pp.id='${a.previewId}'`); assert(!reopened.error && row.project === 'changes_requested' && row.status === 'revoked' && row.confirmations <= 1 && (confirmed.data?.resultCode === 'SUCCESS' || confirmed.data?.resultCode === 'NOT_FOUND'), 'Confirmation/reopen race left unsafe state'); });
    await test(25, 'Correction and reopen serialize safely', async () => { const id = project('correction-race', 'approved'); const a = await generate(id); const [requested, reopened] = await Promise.all([correction(a.hash), review(id)]); const row = one<{ status: string; preview: string; corrections: number; audits: number }>(`SELECT p.status,pp.status preview,(SELECT count(*)::int FROM public.participant_preview_correction_requests WHERE participant_preview_id=pp.id) corrections,(SELECT count(*)::int FROM public.approval_records WHERE project_id=p.id) audits FROM public.projects p JOIN public.participant_previews pp ON pp.project_id=p.id WHERE pp.id='${a.previewId}'`); assert(row.corrections <= 1 && row.audits <= 1 && ((requested.data?.resultCode === 'SUCCESS' && row.status === 'approved' && row.preview === 'active') || (!reopened.error && row.status === 'changes_requested' && row.preview === 'revoked')), 'Correction/reopen race left mixed state'); });
    await test(17, 'Published direct metadata edit returns PUBLISHED_PROJECT_LOCKED', async () => { const id = project('published', 'published'); const result = await metadata(id, 'Blocked'); assert(!result.error && result.data?.resultCode === 'PUBLISHED_PROJECT_LOCKED', 'Published edit was not locked'); });
    await test(18, 'Published rejection is mutation-free', async () => { const id = project('published-clean', 'published'); const before = snapshot(id); await metadata(id, 'Blocked'); assert(JSON.stringify(snapshot(id)) === JSON.stringify(before), 'Published rejection mutated state'); });
    await test(22, 'Stale expected_updated_at returns STALE_VERSION without partial mutation', async () => { const id = project('stale', 'draft'); const stale = String(snapshot(id).updated_at); await metadata(id, 'Winner'); const result = await service.rpc('update_project_metadata', args(id, 'Loser', stale)); assert(!result.error && result.data?.resultCode === 'STALE_VERSION' && snapshot(id).title === 'Winner', 'Stale update was not safely rejected'); });
    await test(23, 'Repeated Request changes converges without duplicate audit', async () => { const id = project('retry', 'approved'); const first = await review(id); const second = await review(id); assert(!first.error && second.error && count(`SELECT count(*) FROM public.approval_records ar JOIN public.projects p ON p.id=ar.project_id WHERE p.public_id='${id}'`) === 1, 'Retry created duplicate side effects'); });
    await test(26, 'Anon direct access to protected approval-gate RPCs is denied', async () => { const id = project('anon', 'draft'); const row = snapshot(id); const [m, r] = await Promise.all([anon.rpc('update_project_metadata', args(id, 'Anon', String(row.updated_at))), anon.rpc('perform_project_review_action', { p_public_id: id, p_action: 'request_changes', p_comments: null, p_admin_id: ids.admin })]); assert(Boolean(m.error) && Boolean(r.error), 'Anon gained protected RPC access'); });
    await test(27, 'Approval-gate scenarios create no publication side effects', async () => { assert(count(`SELECT count(*) FROM public.published_snapshots WHERE feed_file_name LIKE '${prefix}%'`) === 0 && count(`SELECT count(*) FROM public.media_assets ma JOIN public.projects p ON p.id=ma.project_id WHERE p.public_id LIKE '${prefix}%' AND (ma.is_public_approved OR ma.public_url IS NOT NULL)`) === 0, 'Verifier created publication side effects'); });
  } finally {
    sql(`DELETE FROM public.projects WHERE public_id LIKE '${prefix}%';`);
    sql('CREATE UNIQUE INDEX IF NOT EXISTS uq_participant_previews_one_active_per_project ON public.participant_previews(project_id) WHERE status = \'active\'');
    const residue = count(`SELECT count(*) FROM public.projects WHERE public_id LIKE '${prefix}%'`);
    assert(residue === 0, `Cleanup left ${residue} synthetic projects`);
  }
  console.log('--- Test 28: Independent cleanup verification ---');
  console.log('PASS: Test 28 - All synthetic project, preview, confirmation, correction, audit, taxonomy, and media rows cascaded cleanly.');
  console.log('OVERALL APPROVAL EDIT GATE RUNTIME VERIFICATION RESULT: PASS');
}
main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exit(1); });
