import crypto from 'node:crypto';
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { createClient } from '@supabase/supabase-js';
import { getPermissionsForRoles, hasPermission } from '../auth/permissions';
import { saveAuthorizedProjectMetadata } from '../projects/projectMetadataAuthorization';
import { isLoopbackUrl, parseSupabaseCliEnv } from '../local-development/localEnvironmentFile';

const root = path.resolve(__dirname, '../../../..');
const prefix = `approval-gate-${Date.now().toString(36)}`;
type WorkflowState = { project: { status: string; updated_at: string }; preview: { id: string; status: string; revoked_at: string | null; revoked_by: string | null; snapshot: unknown }; corrections: Array<{ status: string }>; audits: number };
const sql = (query: string) => execSync(`docker exec supabase_db_capstone-impact-platform psql -U postgres -d postgres -At -v ON_ERROR_STOP=1 -c "${query.replace(/"/g, '\\"')}"`, { cwd: root, encoding: 'utf8' }).trim();
const one = <T>(query: string): T => JSON.parse(sql(`SELECT row_to_json(t) FROM (${query}) t`));
const count = (query: string) => Number(sql(query));
function assert(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message); }
const test = async (number: number, name: string, body: () => Promise<void>) => { console.log(`--- Test ${number}: ${name} ---`); await body(); console.log(`PASS: Test ${number} - ${name}.`); };

async function main() {
  const raw = execSync(`"${path.join(root, 'node_modules/.bin/supabase')}" status --workdir "${path.join(root, 'infra')}" -o env`, { cwd: root, encoding: 'utf8' });
  const env = parseSupabaseCliEnv(raw);
  assert(env.API_URL && env.SERVICE_ROLE_KEY && env.ANON_KEY && isLoopbackUrl(env.API_URL), 'Local loopback Supabase is required.');
  const service = createClient(env.API_URL, env.SERVICE_ROLE_KEY, { auth: { autoRefreshToken: false, persistSession: false } });
  const anon = createClient(env.API_URL, env.ANON_KEY, { auth: { autoRefreshToken: false, persistSession: false } });
  const ids = one<{ program: string; discipline: string; industry: string; admin: string; reviewer: string; editor: string }>("SELECT (SELECT id::text FROM public.programs LIMIT 1) program,(SELECT id::text FROM public.disciplines LIMIT 1) discipline,(SELECT id::text FROM public.industry_categories LIMIT 1) industry,(SELECT au.id::text FROM public.admin_users au JOIN public.user_roles ur ON ur.user_id=au.id WHERE ur.role='admin' LIMIT 1) admin,(SELECT au.id::text FROM public.admin_users au JOIN public.user_roles ur ON ur.user_id=au.id WHERE ur.role='reviewer' LIMIT 1) reviewer,(SELECT au.id::text FROM public.admin_users au JOIN public.user_roles ur ON ur.user_id=au.id WHERE ur.role='editor' LIMIT 1) editor");
  const projectIds: string[] = [];
  const project = (name: string, status: string) => {
    const publicId = `${prefix}-${name}`;
    sql(`INSERT INTO public.projects(public_id,title,summary,background,solution,poster_text_public,accessibility_text_public,year,program_id,program_name,discipline,industry,status) VALUES ('${publicId}','Before','Before','Background','Solution','Before poster full text','Before accessibility text',2026,'${ids.program}'::uuid,'Program','Discipline','Industry','${status}')`);
    const projectId = sql(`SELECT id::text FROM public.projects WHERE public_id='${publicId}'`);
    projectIds.push(projectId);
    sql(`INSERT INTO public.media_assets(project_id,asset_type,file_name,storage_bucket,storage_path,mime_type,file_size_bytes,is_public_approved,public_url,public_storage_bucket,public_storage_path) VALUES ('${projectId}'::uuid,'poster_image','poster.png','project-drafts-private','drafts/${publicId}/poster_image/poster.png','image/png',128,false,NULL,NULL,NULL),('${projectId}'::uuid,'poster_pdf','poster.pdf','project-drafts-private','drafts/${publicId}/poster_pdf/poster.pdf','application/pdf',256,false,NULL,NULL,NULL)`);
    return publicId;
  };
  const snapshot = (publicId: string) => one<Record<string, unknown>>(`SELECT p.title,p.summary,p.background,p.solution,p.year,p.program_id::text,p.status,p.updated_at::text,(SELECT json_agg(discipline_id::text ORDER BY discipline_id) FROM public.project_disciplines WHERE project_id=p.id) disciplines,(SELECT json_agg(industry_category_id::text ORDER BY industry_category_id) FROM public.project_industry_categories WHERE project_id=p.id) industries,(SELECT count(*) FROM public.approval_records WHERE project_id=p.id) audits FROM public.projects p WHERE public_id='${publicId}'`);
  const args = (publicId: string, title: string, updatedAt: string, adminId = ids.admin) => ({ p_public_id: publicId, p_title: title, p_summary: `${title} summary`, p_background: `${title} background`, p_solution: `${title} solution`, p_year: 2027, p_program_id: ids.program, p_discipline_ids: [ids.discipline], p_industry_category_ids: [ids.industry], p_expected_updated_at: updatedAt, p_admin_id: adminId, p_poster_text: `${title} poster full text`, p_accessibility_text: `${title} accessibility text` });
  const metadata = async (publicId: string, title: string) => { const row = snapshot(publicId); return service.rpc('update_project_metadata', args(publicId, title, String(row.updated_at))); };
  const review = (publicId: string, adminId = ids.admin, comments = 'runtime request changes') => service.rpc('perform_project_review_action', { p_public_id: publicId, p_action: 'request_changes', p_comments: comments, p_admin_id: adminId });
  const token = () => crypto.randomBytes(32).toString('hex');
  const generate = async (publicId: string) => { const hash = token(); const result = await service.rpc('generate_participant_preview', { p_public_id: publicId, p_admin_id: ids.admin, p_token_hash: hash, p_expires_in_seconds: 3600, p_private_bucket: 'project-drafts-private' }); assert(!result.error && result.data?.resultCode === 'SUCCESS', 'Preview generation failed'); return { hash, previewId: String(result.data.previewId) }; };
  const confirm = (hash: string) => service.rpc('confirm_participant_preview', { p_token_hash: hash });
  const correction = (hash: string) => service.rpc('request_participant_preview_correction', { p_token_hash: hash, p_comment: 'Please correct this preview.' });
  const readiness = (publicId: string) => service.rpc('get_project_publication_readiness', { p_public_id: publicId, p_admin_id: ids.admin, p_private_bucket: 'project-drafts-private' });
  const workflow = (publicId: string, previewId: string) => one<{ state: WorkflowState }>(`SELECT json_build_object('project',json_build_object('status',p.status,'updated_at',p.updated_at::text),'preview',(SELECT json_build_object('id',pp.id::text,'status',pp.status,'revoked_at',pp.revoked_at::text,'revoked_by',pp.revoked_by::text,'snapshot',pp.snapshot) FROM public.participant_previews pp WHERE pp.id='${previewId}'),'corrections',(SELECT coalesce(json_agg(json_build_object('id',r.id::text,'status',r.status,'requested_at',r.requested_at::text,'comment',r.correction_comment,'resolution_started_at',r.resolution_started_at::text,'resolution_started_by',r.resolution_started_by::text,'resolved_at',r.resolved_at::text,'resolved_by',r.resolved_by::text,'replacement_preview_id',r.replacement_preview_id::text) ORDER BY r.id),'[]'::json) FROM public.participant_preview_correction_requests r WHERE r.participant_preview_id='${previewId}'),'audits',(SELECT count(*) FROM public.approval_records WHERE project_id=p.id)) state FROM public.projects p WHERE p.public_id='${publicId}'`).state;
  const baseline = {
    snapshots: count('SELECT count(*) FROM public.published_snapshots'),
    feeds: JSON.stringify((await service.storage.from('public-feeds').list()).data || []),
    assets: JSON.stringify((await service.storage.from('project-public-assets').list()).data || []),
  };
  const assertPublicationBaseline = () => {
    assert(count('SELECT count(*) FROM public.published_snapshots') === baseline.snapshots, 'published_snapshots changed');
    return Promise.all([service.storage.from('public-feeds').list(), service.storage.from('project-public-assets').list()]).then(([feeds, assets]) => {
      assert(!feeds.error && !assets.error && JSON.stringify(feeds.data || []) === baseline.feeds && JSON.stringify(assets.data || []) === baseline.assets, 'Public storage baseline changed');
      assert(count(`SELECT count(*) FROM public.projects WHERE public_id LIKE '${prefix}%' AND status='published' AND public_id NOT IN ('${prefix}-published','${prefix}-published-clean')`) === 0, 'Synthetic project became published');
      assert(count(`SELECT count(*) FROM public.media_assets ma JOIN public.projects p ON p.id=ma.project_id WHERE p.public_id LIKE '${prefix}%' AND (ma.is_public_approved OR ma.public_url IS NOT NULL)`) === 0, 'Synthetic media became public');
    });
  };
  const appAllowsMetadata = async (role: 'admin' | 'reviewer' | 'editor') => {
    const permissions = getPermissionsForRoles([role]); let invoked = false;
    const input = { publicId: 'boundary', title: 'Boundary', summary: 'Boundary', background: 'Boundary', solution: 'Boundary', posterText: 'Boundary poster full text', accessibilityText: 'Boundary accessibility text', year: '2027', programId: ids.program, disciplineIds: [ids.discipline], industryCategoryIds: [ids.industry], expectedUpdatedAt: new Date().toISOString() };
    const result = await saveAuthorizedProjectMetadata(permissions, { loadOptions: async () => ({ programs: [{ id: ids.program, name: 'Program' }], disciplines: [{ id: ids.discipline, name: 'Discipline' }], industryCategories: [{ id: ids.industry, name: 'Industry' }] }), loadProject: async () => null, updateMetadataAtomically: async () => { invoked = true; return { resultCode: 'SUCCESS', metadata: input, auditRecordId: crypto.randomUUID() }; } }, input, ids.admin);
    return { permissions, result, invoked };
  };
  try {
    await test(1, 'Draft metadata edit persists scalars, taxonomies, and draft status', async () => { const id = project('draft', 'draft'); const result = await metadata(id, 'Draft changed'); assert(!result.error && result.data?.resultCode === 'SUCCESS' && snapshot(id).title === 'Draft changed' && snapshot(id).status === 'draft', 'Draft mutation failed'); });
    await test(2, 'changes_requested metadata edit preserves state', async () => { const id = project('changes', 'changes_requested'); const result = await metadata(id, 'Changes changed'); assert(!result.error && result.data?.resultCode === 'SUCCESS' && snapshot(id).status === 'changes_requested', 'changes_requested mutation failed'); });
    await test(3, 'Approved direct metadata edit returns APPROVAL_REOPEN_REQUIRED', async () => { const id = project('approved-gate', 'approved'); const result = await metadata(id, 'Rejected'); assert(!result.error && result.data?.resultCode === 'APPROVAL_REOPEN_REQUIRED', 'Approved edit was not rejected'); });
    await test(4, 'Approved rejection is mutation-free', async () => { const id = project('approved-clean', 'approved'); const before = snapshot(id); await metadata(id, 'Rejected'); assert(JSON.stringify(snapshot(id)) === JSON.stringify(before), 'Approved rejection mutated state'); });
    await test(5, 'Approved project without preview reopens through Request changes', async () => { const id = project('reopen', 'approved'); const result = await review(id); assert(!result.error && result.data?.status === 'changes_requested' && snapshot(id).status === 'changes_requested', 'Approved project did not reopen'); });
    await test(6, 'Reopen creates exactly one correctly attributed audit record', async () => { const id = project('audit', 'approved'); await review(id, ids.reviewer, '  bounded comment  '); const audit = one<{ n: number; actor: string; action: string; from: string; to: string; comment: string }>(`SELECT count(*)::int n,max(admin_id::text) actor,max(action_taken) action,max(from_status) "from",max(to_status) "to",max(comments) comment FROM public.approval_records ar JOIN public.projects p ON p.id=ar.project_id WHERE p.public_id='${id}'`); assert(audit.n === 1 && audit.actor === ids.reviewer && audit.action === 'request_changes' && audit.from === 'approved' && audit.to === 'changes_requested' && audit.comment === 'bounded comment', 'Audit record was incorrect'); });
    await test(7, 'Active Preview A is revoked atomically when reopening', async () => { const id = project('preview-revoke', 'approved'); const a = await generate(id); await review(id, ids.reviewer); const row = one<{ status: string; revoked_by: string }>(`SELECT status,revoked_by::text FROM public.participant_previews WHERE id='${a.previewId}'`); assert(row.status === 'revoked' && row.revoked_by === ids.reviewer, 'Preview A was not revoked'); });
    await test(8, 'Revoked Preview A token cannot resolve, confirm, or request correction', async () => { const id = project('token', 'approved'); const a = await generate(id); await review(id); const [resolved, confirmed, corrected] = await Promise.all([service.rpc('resolve_participant_preview', { p_token_hash: a.hash }), confirm(a.hash), correction(a.hash)]); assert(resolved.data?.resultCode === 'NOT_FOUND' && confirmed.data?.resultCode === 'NOT_FOUND' && corrected.data?.resultCode === 'NOT_FOUND', 'Revoked token remained usable'); });
    await test(9, 'Confirmed Preview A history survives reopen', async () => { const id = project('confirmed-history', 'approved'); const a = await generate(id); await confirm(a.hash); const before = workflow(id, a.previewId); await review(id); const after = workflow(id, a.previewId); assert(JSON.stringify(after.corrections) === JSON.stringify(before.corrections) && after.preview.status === 'revoked', 'Confirmed history changed'); });
    await test(10, 'Historical Preview A confirmation cannot authorize edited state', async () => { const id = project('historical-readiness', 'approved'); const a = await generate(id); await confirm(a.hash); await review(id); await metadata(id, 'Edited after reopen'); await service.rpc('perform_project_review_action', { p_public_id: id, p_action: 'approve', p_comments: 'reapprove', p_admin_id: ids.admin }); const ready = await readiness(id); assert(!ready.error && ready.data?.resultCode !== 'READY', 'Historical confirmation restored readiness'); });
    await test(11, 'Fresh Preview B begins unconfirmed and not ready', async () => { const id = project('fresh-b', 'approved'); const a = await generate(id); await confirm(a.hash); await review(id); await metadata(id, 'Changed'); await service.rpc('perform_project_review_action', { p_public_id: id, p_action: 'approve', p_comments: 'reapprove', p_admin_id: ids.admin }); const b = await generate(id); const ready = await readiness(id); assert(a.previewId !== b.previewId && count(`SELECT count(*) FROM public.participant_preview_confirmations WHERE participant_preview_id='${b.previewId}'`) === 0 && ready.data?.resultCode !== 'READY', 'Fresh Preview B was not independent'); });
    await test(12, 'Confirming exact Preview B restores READY', async () => { const id = project('confirm-b', 'approved'); const a = await generate(id); await confirm(a.hash); await review(id); await metadata(id, 'Changed'); await service.rpc('perform_project_review_action', { p_public_id: id, p_action: 'approve', p_comments: 'reapprove', p_admin_id: ids.admin }); const b = await generate(id); await confirm(b.hash); const ready = await readiness(id); assert(ready.data?.resultCode === 'READY' && count(`SELECT count(*) FROM public.participant_preview_confirmations WHERE participant_preview_id IN ('${a.previewId}','${b.previewId}')`) === 2, 'Preview B did not establish readiness'); });
    await test(13, 'Open correction blocks generic Request changes without mutation', async () => { const id = project('open-correction', 'approved'); const a = await generate(id); await correction(a.hash); const before = workflow(id, a.previewId); const result = await review(id); const after = workflow(id, a.previewId); assert(!result.error && result.data?.resultCode === 'CORRECTION_RESOLUTION_REQUIRED' && JSON.stringify(after) === JSON.stringify(before), 'Open correction rejection mutated workflow state'); });
    await test(14, 'in_progress correction remains authoritative', async () => { const id = project('in-progress', 'approved'); const a = await generate(id); await correction(a.hash); await service.rpc('start_participant_preview_correction_resolution', { p_public_id: id, p_admin_id: ids.admin }); const before = workflow(id, a.previewId); await review(id); assert(JSON.stringify(workflow(id, a.previewId)) === JSON.stringify(before), 'Generic action corrupted in-progress correction'); });
    await test(15, 'Dedicated correction-resolution workflow preserves its lifecycle', async () => { const id = project('resolution', 'approved'); const a = await generate(id); await correction(a.hash); const result = await service.rpc('start_participant_preview_correction_resolution', { p_public_id: id, p_admin_id: ids.admin }); const state = workflow(id, a.previewId); assert(!result.error && result.data?.resultCode === 'SUCCESS' && state.project.status === 'changes_requested' && state.preview.status === 'revoked' && state.corrections[0].status === 'in_progress', 'Correction-resolution lifecycle regressed'); });
    await test(16, 'Contradictory active previews fail closed without mutation', async () => { const id = project('ambiguous', 'approved'); const a = await generate(id); const projectId = sql(`SELECT id::text FROM public.projects WHERE public_id='${id}'`); sql('DROP INDEX public.uq_participant_previews_one_active_per_project'); sql(`INSERT INTO public.participant_previews(project_id,token_hash,snapshot,media_snapshot,status,created_by,expires_at) VALUES ('${projectId}'::uuid,'${token()}','{}'::jsonb,'[]'::jsonb,'active','${ids.admin}'::uuid,now()+interval '1 hour')`); const before = one<unknown>(`SELECT json_agg(json_build_object('id',id::text,'status',status,'revoked_at',revoked_at::text,'revoked_by',revoked_by::text,'snapshot',snapshot) ORDER BY id) FROM public.participant_previews WHERE project_id='${projectId}'`); const audits = count(`SELECT count(*) FROM public.approval_records WHERE project_id='${projectId}'`); const result = await review(id); const after = one<unknown>(`SELECT json_agg(json_build_object('id',id::text,'status',status,'revoked_at',revoked_at::text,'revoked_by',revoked_by::text,'snapshot',snapshot) ORDER BY id) FROM public.participant_previews WHERE project_id='${projectId}'`); assert(!result.error && result.data?.resultCode === 'AMBIGUOUS_ACTIVE_PREVIEW' && snapshot(id).status === 'approved' && JSON.stringify(after) === JSON.stringify(before) && count(`SELECT count(*) FROM public.participant_preview_correction_requests r JOIN public.participant_previews p ON p.id=r.participant_preview_id WHERE p.project_id='${projectId}'`) === 0 && count(`SELECT count(*) FROM public.approval_records WHERE project_id='${projectId}'`) === audits, 'Ambiguous previews were touched'); void a; });
    await test(17, 'Published direct metadata edit returns PUBLISHED_PROJECT_LOCKED', async () => { const id = project('published', 'published'); const result = await metadata(id, 'Blocked'); assert(!result.error && result.data?.resultCode === 'PUBLISHED_PROJECT_LOCKED', 'Published edit was not locked'); });
    await test(18, 'Published rejection is mutation-free', async () => { const id = project('published-clean', 'published'); const before = snapshot(id); await metadata(id, 'Blocked'); assert(JSON.stringify(snapshot(id)) === JSON.stringify(before), 'Published rejection mutated state'); });
    await test(19, 'Editor has app edit authority but cannot review', async () => { const id = project('editor', 'submitted'); const app = await appAllowsMetadata('editor'); const before = snapshot(id); const result = await review(id, ids.editor); assert(hasPermission(app.permissions, 'projects.edit') && !hasPermission(app.permissions, 'projects.review') && app.result.ok && app.invoked && Boolean(result.error) && JSON.stringify(snapshot(id)) === JSON.stringify(before), 'Editor architecture boundary failed'); });
    await test(20, 'Reviewer has app review authority but not edit authority', async () => { const id = project('reviewer', 'submitted'); const app = await appAllowsMetadata('reviewer'); const result = await review(id, ids.reviewer); const audit = one<{ n: number; actor: string }>(`SELECT count(*)::int n,max(admin_id::text) actor FROM public.approval_records ar JOIN public.projects p ON p.id=ar.project_id WHERE p.public_id='${id}'`); assert(hasPermission(app.permissions, 'projects.review') && !hasPermission(app.permissions, 'projects.edit') && !app.result.ok && app.result.code === 'PERMISSION_DENIED' && !app.invoked && !result.error && result.data?.status === 'changes_requested' && audit.n === 1 && audit.actor === ids.reviewer, 'Reviewer architecture boundary failed'); });
    await test(21, 'Admin has app edit and review authority', async () => { const mutable = project('admin-edit', 'draft'); const reviewed = project('admin-review', 'submitted'); const app = await appAllowsMetadata('admin'); const saved = await metadata(mutable, 'Admin changed'); const result = await review(reviewed, ids.admin); const actor = sql(`SELECT max(ar.admin_id::text) FROM public.approval_records ar JOIN public.projects p ON p.id=ar.project_id WHERE p.public_id='${reviewed}'`); assert(hasPermission(app.permissions, 'projects.edit') && hasPermission(app.permissions, 'projects.review') && app.result.ok && app.invoked && saved.data?.resultCode === 'SUCCESS' && !result.error && result.data?.status === 'changes_requested' && actor === ids.admin, 'Admin architecture boundary failed'); });
    await test(22, 'Stale expected_updated_at returns STALE_VERSION without partial mutation', async () => { const id = project('stale', 'draft'); const stale = String(snapshot(id).updated_at); await metadata(id, 'Winner'); const result = await service.rpc('update_project_metadata', { ...args(id, 'Loser', stale), p_admin_id: ids.admin }); assert(!result.error && result.data?.resultCode === 'STALE_VERSION' && snapshot(id).title === 'Winner', 'Stale update was unsafe'); });
    await test(23, 'Repeated Request changes converges without duplicate audit', async () => { const id = project('retry', 'approved'); await review(id); const second = await review(id); assert(Boolean(second.error) && count(`SELECT count(*) FROM public.approval_records ar JOIN public.projects p ON p.id=ar.project_id WHERE p.public_id='${id}'`) === 1, 'Retry created duplicate side effects'); });
    await test(24, 'Confirmation and reopen serialize to one exact valid outcome', async () => { const id = project('confirm-race', 'approved'); const a = await generate(id); const [confirmed, reopened] = await Promise.all([confirm(a.hash), review(id)]); const row = one<{ project: string; preview: string; confirmations: number; audits: number }>(`SELECT p.status project,pp.status preview,(SELECT count(*)::int FROM public.participant_preview_confirmations WHERE participant_preview_id=pp.id) confirmations,(SELECT count(*)::int FROM public.approval_records WHERE project_id=p.id) audits FROM public.projects p JOIN public.participant_previews pp ON pp.project_id=p.id WHERE pp.id='${a.previewId}'`); const confirmationWins = confirmed.data?.resultCode === 'SUCCESS' && row.confirmations === 1; const reopenWins = confirmed.data?.resultCode === 'NOT_FOUND' && row.confirmations === 0; assert(!reopened.error && row.project === 'changes_requested' && row.preview === 'revoked' && row.audits === 1 && (confirmationWins || reopenWins), 'Confirmation/reopen race produced mismatched state'); console.log(`Race winner: ${confirmationWins ? 'confirmation' : 'reopen'}; project=${row.project}, preview=${row.preview}, confirmations=${row.confirmations}, audits=${row.audits}`); });
    await test(25, 'Correction and reopen serialize to one exact valid outcome', async () => { let correctionWins = 0; let reopenWins = 0; for (let iteration = 1; iteration <= 10; iteration++) { const id = project(`correction-race-${iteration}`, 'approved'); const a = await generate(id); const [requested, reopened] = await Promise.all([correction(a.hash), review(id)]); const row = one<{ project: string; preview: string; corrections: number; audits: number; correction_status: string | null }>(`SELECT p.status project,pp.status preview,(SELECT count(*)::int FROM public.participant_preview_correction_requests WHERE participant_preview_id=pp.id) corrections,(SELECT count(*)::int FROM public.approval_records WHERE project_id=p.id) audits,(SELECT status FROM public.participant_preview_correction_requests WHERE participant_preview_id=pp.id) correction_status FROM public.projects p JOIN public.participant_previews pp ON pp.project_id=p.id WHERE pp.id='${a.previewId}'`); const correctionWon = requested.data?.resultCode === 'SUCCESS' && reopened.data?.resultCode === 'CORRECTION_RESOLUTION_REQUIRED' && row.project === 'approved' && row.preview === 'active' && row.corrections === 1 && row.correction_status === 'open' && row.audits === 0; const reopenWon = requested.data?.resultCode === 'NOT_FOUND' && !reopened.error && row.project === 'changes_requested' && row.preview === 'revoked' && row.corrections === 0 && row.audits === 1; assert(correctionWon || reopenWon, `Correction/reopen mixed state in iteration ${iteration}: ${JSON.stringify({ requested: requested.data?.resultCode, reopened: reopened.data?.resultCode, row })}`); if (correctionWon) correctionWins++; else reopenWins++; } console.log(`Race iterations=10, correctionWins=${correctionWins}, reopenWins=${reopenWins}, mixedOutcomes=0`); });
    await test(26, 'Anon and authenticated non-service clients cannot execute protected RPCs', async () => { const id = project('non-service', 'draft'); const row = snapshot(id); const credentials = JSON.parse(fs.readFileSync(path.join(root, 'apps/admin-cms/.local-users.json'), 'utf8')) as { users: Record<string, string> }; const password = credentials.users['local.editor@capstone.test']; assert(password, 'Local editor credentials missing'); const authenticated = createClient(env.API_URL!, env.ANON_KEY!, { auth: { autoRefreshToken: false, persistSession: false } }); const signIn = await authenticated.auth.signInWithPassword({ email: 'local.editor@capstone.test', password }); assert(!signIn.error && signIn.data.session, 'Could not establish authenticated local non-service session'); const call = (client: typeof anon) => Promise.all([client.rpc('update_project_metadata', args(id, 'Blocked', String(row.updated_at))), client.rpc('perform_project_review_action', { p_public_id: id, p_action: 'request_changes', p_comments: null, p_admin_id: ids.admin })]); const [anonResults, authenticatedResults] = await Promise.all([call(anon), call(authenticated)]); assert(anonResults.every((result) => Boolean(result.error)) && authenticatedResults.every((result) => Boolean(result.error)) && JSON.stringify(snapshot(id)) === JSON.stringify(row), 'Non-service client executed protected RPC'); });
    await test(27, 'Approval-gate scenarios preserve database and public-storage baselines', async () => { await assertPublicationBaseline(); });
  } finally {
    sql(`DELETE FROM public.projects WHERE id IN (${projectIds.map((id) => `'${id}'::uuid`).join(',') || 'NULL'})`);
    sql("CREATE UNIQUE INDEX IF NOT EXISTS uq_participant_previews_one_active_per_project ON public.participant_previews(project_id) WHERE status = 'active'");
  }
  await test(28, 'Independent cleanup verifies all child tables and public baselines', async () => { const idsSql = projectIds.map((id) => `'${id}'::uuid`).join(',') || 'NULL'; const checks = [
    `SELECT count(*) FROM public.projects WHERE id IN (${idsSql})`,
    `SELECT count(*) FROM public.participant_previews WHERE project_id IN (${idsSql})`,
    `SELECT count(*) FROM public.participant_preview_confirmations c JOIN public.participant_previews p ON p.id=c.participant_preview_id WHERE p.project_id IN (${idsSql})`,
    `SELECT count(*) FROM public.participant_preview_correction_requests r JOIN public.participant_previews p ON p.id=r.participant_preview_id WHERE p.project_id IN (${idsSql})`,
    `SELECT count(*) FROM public.approval_records WHERE project_id IN (${idsSql})`,
    `SELECT count(*) FROM public.project_disciplines WHERE project_id IN (${idsSql})`,
    `SELECT count(*) FROM public.project_industry_categories WHERE project_id IN (${idsSql})`,
    `SELECT count(*) FROM public.media_assets WHERE project_id IN (${idsSql})`,
  ].map(count); assert(checks.every((value) => value === 0), `Cleanup residue: ${checks.join(',')}`); await assertPublicationBaseline(); });
  console.log('OVERALL APPROVAL EDIT GATE RUNTIME VERIFICATION RESULT: PASS');
}
main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exit(1); });
