import { z } from 'zod';

import {
  ASSISTIVE_EVIDENCE_LIMITS,
  assistiveCheckResultSchema,
  sanitizeAssistivePlainText,
  type AssistiveCheckResult,
} from './evidence';
import {
  boundedDuplicateEvidenceText,
  comparePublicIds,
  DUPLICATE_SHORTLIST_LIMITS,
  type RankedDuplicateCandidate,
} from '../duplicate-detection/duplicateRanker';

/**
 * Phase 3 durable persistence contract for the Phase 2 deterministic assistive observations.
 *
 * Everything here is non-authoritative. A persisted run or finding never changes project status,
 * approval, publication, archival, publication readiness, or project metadata, and this module
 * deliberately imports nothing from the project, review, publication, or import domains.
 */

/**
 * Identity of the deterministic evaluation that produced a run. It is part of the run's uniqueness
 * key, so bumping it is how a changed algorithm earns a new durable run for unchanged content.
 */
export const ASSISTIVE_PIPELINE_VERSION = 'assistive-deterministic-checks/v3';

/** Version tag stored inside every persisted evidence object. */
export const ASSISTIVE_FINDING_EVIDENCE_VERSION = 'assistive-finding-evidence/v1';
export const ASSISTIVE_DUPLICATE_EVIDENCE_VERSION = 'assistive-finding-evidence/v2';
export const ASSISTIVE_LANGUAGE_EVIDENCE_VERSION = 'assistive-finding-evidence/v3';
export const ASSISTIVE_LANGUAGE_POLICY_SHA256 =
  '3984b958741a5103791524d48ba262a81ef829695ddc122a728c12cc3e689148';

export const ASSISTIVE_PERSISTENCE_LIMITS = {
  findingsPerRun: 50,
  /**
   * Application ceiling for one serialized evidence object, deliberately below the database
   * ceiling below. PostgreSQL renders `jsonb::text` with a space after every `:` and `,`, so the
   * stored text is a little longer than `JSON.stringify` output; keeping the application bound
   * lower guarantees the strict contract rejects an oversized payload before the database has to.
   */
  evidenceJsonCharacters: 8000,
  /** Mirror of the `check_assistive_finding_evidence_size` constraint in migration 0030. */
  databaseEvidenceJsonCharacters: 8192,
  pipelineVersionCharacters: 64,
} as const;

/** Lowercase SHA-256 hexadecimal. Uppercase, truncated, and arbitrary strings all fail closed. */
export const ASSISTIVE_INPUT_HASH_PATTERN = /^[a-f0-9]{64}$/;

export const ASSISTIVE_PIPELINE_VERSION_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*\/v[1-9][0-9]*$/;

/**
 * Canonical UUID text as PostgreSQL itself accepts it, for identifiers that arrive from a database
 * row rather than being generated here.
 *
 * PostgreSQL's `uuid` type validates the 8-4-4-4-12 hexadecimal form and is indifferent to RFC 9562
 * version and variant bits. Zod's `z.uuid()` additionally demands a recognised version nibble, so it
 * rejects identifiers a `uuid` column stores happily — including this repository's synthetic seed
 * identities, whose project rows carry ids of the shape `e0000000-0000-0000-0000-000000000001` and
 * whose media rows carry `f0000000-...`. Parsing those with `z.uuid()` fails every seeded project
 * closed before it reaches the database.
 *
 * Apply this only where the value is a row identifier the database or the seed supplied. Everything
 * generated by `gen_random_uuid()` keeps `z.uuid()`, which is deliberate for the job claim token:
 * it is a fencing token, and widening the shape it accepts would weaken that guarantee.
 *
 * This restates `postgresUuidSchema` from the project metadata domain rather than importing it. The
 * dependency boundary asserted in `__tests__/persistenceBoundary.test.ts` allows this module no
 * import outside the assistive domain, so the concept is duplicated on purpose and kept in sync by
 * that intent rather than by a shared symbol.
 */
export const postgresCanonicalUuidSchema = z.string().regex(
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  'Must be a canonical UUID.',
);

export const assistiveInputHashSchema = z.string().regex(
  ASSISTIVE_INPUT_HASH_PATTERN,
  'Input hash must be lowercase SHA-256 hexadecimal.',
);

export const assistivePipelineVersionSchema = z.string()
  .max(ASSISTIVE_PERSISTENCE_LIMITS.pipelineVersionCharacters)
  .regex(ASSISTIVE_PIPELINE_VERSION_PATTERN, 'Pipeline version must be a bounded versioned identifier.');

const checkResultShape = assistiveCheckResultSchema.shape;

/**
 * The persisted evidence object. Every bound is inherited directly from the Phase 2 result schema
 * rather than restated, so persistence can never widen what Phase 2 already decided is bounded
 * plain text. Only useful comparison evidence is stored: no reasoning trace, no raw transcript, no
 * prompt, no provider response, no URL, no credential.
 */
const persistedAssistiveEvidenceV1Schema = z.object({
  version: z.literal(ASSISTIVE_FINDING_EVIDENCE_VERSION),
  evidenceExcerpt: checkResultShape.evidenceExcerpt,
  pageNumber: checkResultShape.pageNumber,
  boundingBox: checkResultShape.boundingBox,
  metadataValue: checkResultShape.metadataValue,
  normalizedMetadataValue: checkResultShape.normalizedMetadataValue,
  candidateValue: checkResultShape.candidateValue,
  normalizedCandidateValue: checkResultShape.normalizedCandidateValue,
  explanation: checkResultShape.explanation.refine(
    (value) => value.length > 0,
    'Explanation must not be empty.',
  ),
}).strict();

const boundedDuplicateText = (maximum: number) => z.string().max(maximum)
  .refine((value) => !/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/.test(value), 'Must be plain text.');

/**
 * The durable candidate contract states what the selected deterministic ranker actually produces,
 * not a superset of it. Canonical equality includes the normalized title and is the only comparison
 * that scores 1, so a persisted candidate claiming otherwise describes a run that cannot have
 * happened and is refused rather than stored. None of this is a duplicate decision: no score is a
 * threshold, and staff remain the only party who decide whether two projects are the same work.
 */
export const persistedDuplicateCandidateSchema = z.object({
  rank: z.number().int().min(1).max(DUPLICATE_SHORTLIST_LIMITS.shortlist),
  publicId: boundedDuplicateText(DUPLICATE_SHORTLIST_LIMITS.publicId)
    .regex(/^[A-Za-z0-9_-]+$/, 'Candidate public ID must be route-safe.'),
  title: boundedDuplicateText(DUPLICATE_SHORTLIST_LIMITS.title),
  summaryExcerpt: boundedDuplicateText(DUPLICATE_SHORTLIST_LIMITS.summaryExcerpt),
  lexicalScore: z.number().finite().min(0).max(1),
  exactContentMatch: z.boolean(),
  normalizedTitleMatch: z.boolean(),
}).strict().superRefine((candidate, context) => {
  if (candidate.exactContentMatch && !candidate.normalizedTitleMatch) {
    context.addIssue({
      code: 'custom',
      path: ['normalizedTitleMatch'],
      message: 'Canonical equality includes the normalized title, so an exact match matches it too.',
    });
  }
  if (candidate.exactContentMatch && candidate.lexicalScore !== 1) {
    context.addIssue({
      code: 'custom',
      path: ['lexicalScore'],
      message: 'An exact content match scores exactly 1.',
    });
  }
  if (!candidate.exactContentMatch
    && candidate.lexicalScore > DUPLICATE_SHORTLIST_LIMITS.inexactScoreCeiling) {
    context.addIssue({
      code: 'custom',
      path: ['lexicalScore'],
      message: 'A candidate that is not an exact content match is capped below 1.',
    });
  }
});

export type PersistedDuplicateCandidate = z.infer<typeof persistedDuplicateCandidateSchema>;

/**
 * True when the shortlist contains the signal that upgrades the finding from information to review.
 * The converter and both database boundaries derive the outcome and reason from this one predicate,
 * so the three can never disagree about what the same candidate list means.
 */
export function shortlistHasExactOrNormalizedMatch(
  candidates: readonly Pick<PersistedDuplicateCandidate, 'exactContentMatch' | 'normalizedTitleMatch'>[],
): boolean {
  return candidates.some((candidate) => candidate.exactContentMatch || candidate.normalizedTitleMatch);
}

const persistedAssistiveEvidenceV2Schema = persistedAssistiveEvidenceV1Schema.extend({
  version: z.literal(ASSISTIVE_DUPLICATE_EVIDENCE_VERSION),
  duplicateCandidates: z.array(persistedDuplicateCandidateSchema)
    .min(1)
    .max(DUPLICATE_SHORTLIST_LIMITS.shortlist),
}).strict().superRefine((evidence, context) => {
  const publicIds = new Set<string>();
  evidence.duplicateCandidates.forEach((candidate, index) => {
    if (candidate.rank !== index + 1) {
      context.addIssue({ code: 'custom', path: ['duplicateCandidates', index, 'rank'], message: 'Candidate ranks must be contiguous and ordered.' });
    }
    if (publicIds.has(candidate.publicId)) {
      context.addIssue({ code: 'custom', path: ['duplicateCandidates', index, 'publicId'], message: 'Candidate public IDs must be unique.' });
    }
    publicIds.add(candidate.publicId);
    /**
     * The evidence calls itself a ranked shortlist, so the stored order must be the order the
     * selected ranker produces: descending lexical score, then the deterministic public-ID tie
     * breaker. Nothing is re-scored here; only the supplied bounded evidence is checked.
     */
    const previous = evidence.duplicateCandidates[index - 1];
    if (previous === undefined) return;
    if (candidate.lexicalScore > previous.lexicalScore) {
      context.addIssue({ code: 'custom', path: ['duplicateCandidates', index, 'lexicalScore'], message: 'Candidate scores must not increase with rank.' });
    } else if (candidate.lexicalScore === previous.lexicalScore
      && comparePublicIds(previous.publicId, candidate.publicId) >= 0) {
      context.addIssue({ code: 'custom', path: ['duplicateCandidates', index, 'publicId'], message: 'Equal-score candidates must be ordered by ascending public ID.' });
    }
  });
});

const languageEvidenceText = (maximum: number) => z.string()
  .refine((value) => Array.from(value).length <= maximum, `Must contain at most ${maximum} Unicode code points.`)
  .refine((value) => !/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/.test(value), 'Must be plain text.');

export const persistedAssistiveEvidenceV3Schema = z.object({
  version: z.literal(ASSISTIVE_LANGUAGE_EVIDENCE_VERSION),
  startOffset: z.number().int().min(0).max(DUPLICATE_SHORTLIST_LIMITS.background),
  endOffset: z.number().int().min(0).max(DUPLICATE_SHORTLIST_LIMITS.background),
  offsetUnit: z.literal('UNICODE_CODE_POINTS'),
  originalSourceSpan: languageEvidenceText(ASSISTIVE_EVIDENCE_LIMITS.value),
  contextExcerpt: languageEvidenceText(ASSISTIVE_EVIDENCE_LIMITS.excerpt),
  languageCategory: languageEvidenceText(64).regex(/^[A-Z][A-Z0-9_]*$/),
  ruleId: languageEvidenceText(100).regex(/^[A-Za-z0-9][A-Za-z0-9_.-]*$/),
  providerId: z.literal('LANGUAGETOOL'),
  providerVersion: z.literal('6.6'),
  suggestions: z.array(languageEvidenceText(100).refine((value) => value.trim().length > 0))
    .max(3)
    .refine((values) => new Set(values).size === values.length, 'Suggestions must be unique.'),
  explanation: languageEvidenceText(ASSISTIVE_EVIDENCE_LIMITS.explanation)
    .refine((value) => value.length > 0, 'Explanation must not be empty.'),
  inputHash: assistiveInputHashSchema,
  pipelineVersion: z.literal(ASSISTIVE_PIPELINE_VERSION),
  policySha256: z.literal(ASSISTIVE_LANGUAGE_POLICY_SHA256),
}).strict().superRefine((evidence, context) => {
  if (evidence.endOffset < evidence.startOffset) {
    context.addIssue({ code: 'custom', path: ['endOffset'], message: 'End offset must not precede start offset.' });
  }
  if (Array.from(evidence.originalSourceSpan).length !== evidence.endOffset - evidence.startOffset) {
    context.addIssue({ code: 'custom', path: ['originalSourceSpan'], message: 'Source span length must match canonical offsets.' });
  }
});

export const persistedAssistiveEvidenceSchema = z.discriminatedUnion('version', [
  persistedAssistiveEvidenceV1Schema,
  persistedAssistiveEvidenceV2Schema,
  persistedAssistiveEvidenceV3Schema,
]);

export type PersistedAssistiveEvidence = z.infer<typeof persistedAssistiveEvidenceSchema>;

/**
 * The score is persisted as an explicit kind plus value. Phase 0 measured that this number is
 * lexical/edit evidence, not confidence and not a calibrated probability, and naming the kind in
 * the durable record stops a later reader treating a bare scalar as certainty.
 */
export const persistedAssistiveFindingSchema = z.object({
  checkType: checkResultShape.checkType,
  outcome: checkResultShape.outcome,
  classification: checkResultShape.classification,
  reasonCode: checkResultShape.reasonCode,
  affectedField: checkResultShape.affectedField,
  origin: checkResultShape.origin,
  scoreKind: z.literal('LEXICAL_SIMILARITY').nullable(),
  scoreValue: z.number().finite().min(0).max(1).nullable(),
  evidence: persistedAssistiveEvidenceSchema,
}).strict().superRefine((finding, context) => {
  if ((finding.scoreKind === null) !== (finding.scoreValue === null)) {
    context.addIssue({ code: 'custom', message: 'Score kind and score value must both be present or both absent.' });
  }
  if (JSON.stringify(finding.evidence).length > ASSISTIVE_PERSISTENCE_LIMITS.evidenceJsonCharacters) {
    context.addIssue({ code: 'custom', message: 'Persisted evidence exceeds the bounded size.' });
  }
  const isDuplicate = finding.checkType === 'DUPLICATE_SHORTLIST';
  const isLanguage = finding.checkType === 'LANGUAGE_SUGGESTION';
  const expectedEvidenceVersion = isDuplicate
    ? ASSISTIVE_DUPLICATE_EVIDENCE_VERSION
    : isLanguage ? ASSISTIVE_LANGUAGE_EVIDENCE_VERSION : ASSISTIVE_FINDING_EVIDENCE_VERSION;
  if (finding.evidence.version !== expectedEvidenceVersion) {
    context.addIssue({ code: 'custom', message: 'Finding type and evidence version are incoherent.' });
  }
  if (isDuplicate && (finding.scoreKind !== null || finding.scoreValue !== null)) {
    context.addIssue({ code: 'custom', message: 'A shortlist must not carry an ambiguous finding-level score.' });
  }
  if (isDuplicate && !['EXACT_OR_NORMALIZED_DUPLICATE_PRESENT', 'LEXICAL_DUPLICATE_SHORTLIST'].includes(finding.reasonCode)) {
    context.addIssue({ code: 'custom', message: 'Duplicate shortlist reason is invalid.' });
  }
  if (!isDuplicate && ['EXACT_OR_NORMALIZED_DUPLICATE_PRESENT', 'LEXICAL_DUPLICATE_SHORTLIST'].includes(finding.reasonCode)) {
    context.addIssue({ code: 'custom', message: 'Duplicate shortlist reasons cannot be used by other checks.' });
  }
  const languageReasons = [
    'LANGUAGE_SPELLING', 'LANGUAGE_GRAMMAR', 'LANGUAGE_PUNCTUATION',
    'LANGUAGE_CAPITALIZATION', 'LANGUAGE_REPEATED_WORD',
  ];
  if (isLanguage) {
    if (finding.outcome !== 'REVIEW' || finding.classification !== 'NON_BLOCKING'
      || finding.origin !== 'LOCAL_LANGUAGE_PROVIDER'
      || !['title', 'summary', 'background', 'solution'].includes(finding.affectedField)
      || !languageReasons.includes(finding.reasonCode)
      || finding.scoreKind !== null || finding.scoreValue !== null) {
      context.addIssue({ code: 'custom', message: 'Language suggestion metadata is incoherent.' });
    }
    if (finding.reasonCode === 'LANGUAGE_SPELLING'
      && finding.evidence.version === ASSISTIVE_LANGUAGE_EVIDENCE_VERSION
      && finding.evidence.suggestions.length === 0) {
      context.addIssue({ code: 'custom', path: ['evidence', 'suggestions'], message: 'A spelling finding requires at least one suggestion.' });
    }
  } else if (languageReasons.includes(finding.reasonCode)
    || finding.origin === 'LOCAL_LANGUAGE_PROVIDER'
    || ['summary', 'background', 'solution'].includes(finding.affectedField)) {
    context.addIssue({ code: 'custom', message: 'Language-only metadata cannot be used by another finding type.' });
  }
  if (isDuplicate && finding.evidence.version === ASSISTIVE_DUPLICATE_EVIDENCE_VERSION) {
    const hasExactOrNormalized = shortlistHasExactOrNormalizedMatch(finding.evidence.duplicateCandidates);
    const expectedOutcome = hasExactOrNormalized ? 'REVIEW' : 'INFORMATION';
    const expectedReason = hasExactOrNormalized
      ? 'EXACT_OR_NORMALIZED_DUPLICATE_PRESENT'
      : 'LEXICAL_DUPLICATE_SHORTLIST';
    if (finding.outcome !== expectedOutcome) {
      context.addIssue({ code: 'custom', path: ['outcome'], message: `A shortlist ${hasExactOrNormalized ? 'containing' : 'without'} an exact or normalized-title candidate must be ${expectedOutcome}.` });
    }
    if (finding.reasonCode !== expectedReason) {
      context.addIssue({ code: 'custom', path: ['reasonCode'], message: `A shortlist ${hasExactOrNormalized ? 'containing' : 'without'} an exact or normalized-title candidate must carry ${expectedReason}.` });
    }
  }
});

export type PersistedAssistiveFinding = z.infer<typeof persistedAssistiveFindingSchema>;

export const ASSISTIVE_RUN_FAILURE_CODES = [
  'EXTRACTION_CONTRACT_REJECTED',
  'EXTRACTION_FAILED',
  'INTERNAL_FAILURE',
] as const;

export type AssistiveRunFailureCode = (typeof ASSISTIVE_RUN_FAILURE_CODES)[number];

/**
 * A Phase 3 run is durable only in a terminal state, because it is written after the deterministic
 * evaluation has already finished. Worker claiming, leasing, attempts, and cancellation are Phase 4
 * job coordination and are deliberately absent from the run model.
 */
export const assistiveRunPersistenceInputSchema = z.object({
  projectId: postgresCanonicalUuidSchema,
  inputHash: assistiveInputHashSchema,
  pipelineVersion: assistivePipelineVersionSchema,
  status: z.enum(['COMPLETED', 'FAILED']),
  failureCode: z.enum(ASSISTIVE_RUN_FAILURE_CODES).nullable(),
  findings: z.array(persistedAssistiveFindingSchema).max(ASSISTIVE_PERSISTENCE_LIMITS.findingsPerRun),
}).strict().superRefine((run, context) => {
  if (run.status === 'COMPLETED' && run.failureCode !== null) {
    context.addIssue({ code: 'custom', message: 'A completed run must not carry a failure code.' });
  }
  if (run.status === 'FAILED' && run.failureCode === null) {
    context.addIssue({ code: 'custom', message: 'A failed run must carry a bounded failure code.' });
  }
  if (run.status === 'COMPLETED' && run.findings.length === 0) {
    context.addIssue({ code: 'custom', message: 'A completed run must persist at least one finding.' });
  }
  if (run.status === 'FAILED' && run.findings.length > 0) {
    context.addIssue({ code: 'custom', message: 'A failed run must not persist findings.' });
  }
});

export type AssistiveRunPersistenceInput = z.infer<typeof assistiveRunPersistenceInputSchema>;

export const ASSISTIVE_DISPOSITIONS = ['UNREVIEWED', 'REVIEWED', 'IGNORED'] as const;

export type AssistiveDisposition = (typeof ASSISTIVE_DISPOSITIONS)[number];

/**
 * Only these two may be recorded. There is deliberately no "accepted" or "applied" disposition:
 * nothing in Phase 3 updates authoritative metadata, so no durable value may imply that it did.
 */
export const ASSISTIVE_RECORDABLE_DISPOSITIONS = ['REVIEWED', 'IGNORED'] as const;

export type AssistiveRecordableDisposition = (typeof ASSISTIVE_RECORDABLE_DISPOSITIONS)[number];

export const assistiveRecordableDispositionSchema = z.enum(ASSISTIVE_RECORDABLE_DISPOSITIONS);

/** Bounded read shape returned by `get_latest_assistive_validation_run`. */
export const storedAssistiveRunSchema = z.object({
  runId: z.uuid(),
  projectId: postgresCanonicalUuidSchema,
  inputHash: assistiveInputHashSchema,
  pipelineVersion: assistivePipelineVersionSchema,
  status: z.enum(['COMPLETED', 'FAILED']),
  failureCode: z.enum(ASSISTIVE_RUN_FAILURE_CODES).nullable(),
  createdAt: z.string().min(1),
}).strict().superRefine((run, context) => {
  if (run.status === 'COMPLETED' && run.failureCode !== null) {
    context.addIssue({ code: 'custom', message: 'A stored completed run must not carry a failure code.' });
  }
  if (run.status === 'FAILED' && run.failureCode === null) {
    context.addIssue({ code: 'custom', message: 'A stored failed run must carry a bounded failure code.' });
  }
});

export type StoredAssistiveRun = z.infer<typeof storedAssistiveRunSchema>;

export const storedAssistiveFindingSchema = z.object({
  findingId: z.uuid(),
  /** Database-derived position within the run; the caller never supplies it. */
  ordinal: z.number().int().min(1).max(ASSISTIVE_PERSISTENCE_LIMITS.findingsPerRun),
  checkType: checkResultShape.checkType,
  outcome: checkResultShape.outcome,
  classification: checkResultShape.classification,
  reasonCode: checkResultShape.reasonCode,
  affectedField: checkResultShape.affectedField,
  origin: checkResultShape.origin,
  scoreKind: z.literal('LEXICAL_SIMILARITY').nullable(),
  scoreValue: z.number().finite().min(0).max(1).nullable(),
  evidence: persistedAssistiveEvidenceSchema,
  disposition: z.enum(ASSISTIVE_DISPOSITIONS),
  reviewedBy: z.uuid().nullable(),
  reviewedAt: z.string().min(1).nullable(),
  createdAt: z.string().min(1),
}).strict().superRefine((finding, context) => {
  if ((finding.scoreKind === null) !== (finding.scoreValue === null)) {
    context.addIssue({ code: 'custom', message: 'Stored score kind and value must both be present or both absent.' });
  }
  if (finding.disposition === 'UNREVIEWED' && (finding.reviewedBy !== null || finding.reviewedAt !== null)) {
    context.addIssue({ code: 'custom', message: 'An unreviewed finding must not claim reviewer attribution.' });
  }
  if (finding.disposition !== 'UNREVIEWED' && finding.reviewedAt === null) {
    context.addIssue({ code: 'custom', message: 'A dispositioned finding must carry a review timestamp.' });
  }
});

export type StoredAssistiveFinding = z.infer<typeof storedAssistiveFindingSchema>;

/**
 * Converts one in-memory Phase 2 result into its durable representation without reinterpreting it.
 * The outcome, reason, classification, and bounded evidence are carried across unchanged; only the
 * lexical score is restructured into its explicit (kind, value) pair.
 */
export function toPersistedAssistiveFinding(result: AssistiveCheckResult): PersistedAssistiveFinding {
  if (result.checkType === 'DUPLICATE_SHORTLIST') {
    throw new Error('Use toPersistedDuplicateShortlistFinding for duplicate results.');
  }
  if (result.checkType === 'LANGUAGE_SUGGESTION') {
    throw new Error('Use toPersistedLanguageFindings for language suggestions.');
  }
  return persistedAssistiveFindingSchema.parse({
    checkType: result.checkType,
    outcome: result.outcome,
    classification: result.classification,
    reasonCode: result.reasonCode,
    affectedField: result.affectedField,
    origin: result.origin,
    scoreKind: result.lexicalScore === null ? null : 'LEXICAL_SIMILARITY',
    scoreValue: result.lexicalScore,
    evidence: {
      version: ASSISTIVE_FINDING_EVIDENCE_VERSION,
      evidenceExcerpt: result.evidenceExcerpt,
      pageNumber: result.pageNumber,
      boundingBox: result.boundingBox,
      metadataValue: result.metadataValue,
      normalizedMetadataValue: result.normalizedMetadataValue,
      candidateValue: result.candidateValue,
      normalizedCandidateValue: result.normalizedCandidateValue,
      explanation: result.explanation,
    },
  });
}

/**
 * One bounded, browser-safe copy of untrusted candidate prose.
 *
 * A project row is only required to be bounded, not free of interior C0/DEL controls, and the
 * strict persistence schema refuses those characters. Sanitizing here — after ranking and corpus
 * hashing have already consumed the authoritative source, and before anything durable or visible is
 * built from it — keeps one malformed historical record from failing every other project's run,
 * without editing project metadata and without letting a control character reach storage.
 */
function duplicateEvidenceText(value: string, maximum: number): string {
  return sanitizeAssistivePlainText(boundedDuplicateEvidenceText(value, maximum), maximum);
}

export function toPersistedDuplicateShortlistFinding(
  candidates: readonly RankedDuplicateCandidate[],
): PersistedAssistiveFinding | null {
  if (candidates.length === 0) return null;
  const hasExactOrNormalized = shortlistHasExactOrNormalizedMatch(candidates);
  const evidenceCandidates = candidates.map((candidate) => ({
    rank: candidate.rank,
    publicId: candidate.publicId,
    title: duplicateEvidenceText(candidate.title, DUPLICATE_SHORTLIST_LIMITS.title),
    summaryExcerpt: duplicateEvidenceText(candidate.summaryExcerpt, DUPLICATE_SHORTLIST_LIMITS.summaryExcerpt),
    lexicalScore: candidate.lexicalScore,
    exactContentMatch: candidate.exactContentMatch,
    normalizedTitleMatch: candidate.normalizedTitleMatch,
  }));
  return persistedAssistiveFindingSchema.parse({
    checkType: 'DUPLICATE_SHORTLIST',
    outcome: hasExactOrNormalized ? 'REVIEW' : 'INFORMATION',
    classification: 'NON_BLOCKING',
    reasonCode: hasExactOrNormalized
      ? 'EXACT_OR_NORMALIZED_DUPLICATE_PRESENT'
      : 'LEXICAL_DUPLICATE_SHORTLIST',
    affectedField: 'project_content',
    origin: 'DETERMINISTIC_HELPER',
    scoreKind: null,
    scoreValue: null,
    evidence: {
      version: ASSISTIVE_DUPLICATE_EVIDENCE_VERSION,
      evidenceExcerpt: null,
      pageNumber: null,
      boundingBox: null,
      metadataValue: null,
      normalizedMetadataValue: null,
      candidateValue: null,
      normalizedCandidateValue: null,
      explanation: 'Review these lexically similar project records. Staff decide whether any projects are duplicates.',
      duplicateCandidates: evidenceCandidates,
    },
  });
}
