import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

export interface ParsedCliEnv {
  API_URL?: string;
  GRAPHQL_URL?: string;
  DB_URL?: string;
  STUDIO_URL?: string;
  INBUCKET_URL?: string;
  ANON_KEY?: string;
  SERVICE_ROLE_KEY?: string;
  [key: string]: string | undefined;
}

/**
 * Validates whether a URL has a loopback hostname (127.0.0.1, localhost, ::1).
 */
export function isLoopbackUrl(urlStr: string): boolean {
  try {
    const parsed = new URL(urlStr);
    const hostname = parsed.hostname.toLowerCase().replace(/^\[|\]$/g, '');
    return hostname === 'localhost' || hostname === '127.0.0.1' || hostname === '::1';
  } catch {
    return false;
  }
}

function isDescendantOrEqual(parentPath: string, childPath: string): boolean {
  const rel = path.relative(parentPath, childPath);
  return rel === '' || (!rel.startsWith('..') && !path.isAbsolute(rel));
}

/**
 * Validates whether an output path is an authorized destination:
 * 1. Default ignored path inside admin-cms (`apps/admin-cms/.env.local` or `apps/admin-cms/.local-users.json`);
 * 2. Or located inside OS temporary directory (`os.tmpdir()`);
 * 3. Or strictly outside the repository directory.
 * Uses path.relative to prevent false positives on shared prefix sibling paths.
 */
export function validateAllowedOutputPath(targetPath: string, defaultPath: string, repoRoot: string): void {
  const normTarget = path.resolve(targetPath);
  const normDefault = path.resolve(defaultPath);
  const normRepo = path.resolve(repoRoot);
  const normTmp = path.resolve(os.tmpdir());

  let realTarget = normTarget;
  if (fs.existsSync(normTarget)) {
    try {
      realTarget = fs.realpathSync(normTarget);
    } catch {
      // Ignore resolution errors if non-resolvable
    }
  }

  // 1. Allowed if exact default path
  if (normTarget === normDefault || realTarget === normDefault) return;

  // 2. Allowed if inside OS temporary directory
  if (isDescendantOrEqual(normTmp, normTarget) || isDescendantOrEqual(normTmp, realTarget)) return;

  // 3. Reject if inside repository (unless exact default path)
  if (isDescendantOrEqual(normRepo, normTarget) || isDescendantOrEqual(normRepo, realTarget)) {
    throw new Error(
      'Invalid output path: Custom destination must be outside the repository or inside the OS temporary directory.'
    );
  }

  // Otherwise allowed (strictly outside repository directory)
}

/**
 * Parses raw `supabase status -o env` key=value output lines safely.
 */
export function parseSupabaseCliEnv(rawOutput: string): ParsedCliEnv {
  const result: ParsedCliEnv = {};
  const lines = rawOutput.split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

/**
 * Generates `.env.local` contents from parsed Supabase CLI env.
 */
export function buildLocalEnvContent(envData: ParsedCliEnv): string {
  const apiUrl = envData.API_URL || 'http://127.0.0.1:54321';
  const anonKey = envData.ANON_KEY || '';
  const serviceKey = envData.SERVICE_ROLE_KEY || '';

  if (!isLoopbackUrl(apiUrl)) {
    throw new Error('Non-loopback Supabase endpoint rejected.');
  }

  return `# Local Supabase Environment Variables (Generated by npm run supabase:env:local)
NEXT_PUBLIC_SUPABASE_URL=${apiUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${anonKey}

SUPABASE_SERVICE_ROLE_KEY=${serviceKey}
SUPABASE_SECRET_KEY=

SUPABASE_DRAFT_BUCKET=project-drafts-private
SUPABASE_PUBLIC_ASSETS_BUCKET=project-public-assets
SUPABASE_PUBLIC_FEEDS_BUCKET=public-feeds
SUPABASE_PUBLIC_FEED_FILE=capstones-latest.json

GEMINI_API_KEY=
GEMINI_MODEL=gemini-2.5-flash
GEMINI_ASSISTIVE_EXTRACTION_ENABLED=false
`;
}

export interface GenerateEnvOptions {
  outputPath?: string;
  force?: boolean;
  cliOutput?: string;
  workdir?: string;
}

/**
 * Main worker for generating local environment files safely.
 */
export function generateLocalEnvironmentFile(options: GenerateEnvOptions = {}): {
  targetPath: string;
  keysWritten: string[];
} {
  const repoRoot = path.resolve(__dirname, '../../../..');
  const defaultPath = path.resolve(repoRoot, 'apps/admin-cms/.env.local');
  const targetPath = options.outputPath ? path.resolve(options.outputPath) : defaultPath;

  // Validate allowed output path restriction
  validateAllowedOutputPath(targetPath, defaultPath, repoRoot);

  // Check existing file overwrite policy
  if (fs.existsSync(targetPath) && !options.force) {
    throw new Error('File overwrite refused: Target file already exists.');
  }

  // Obtain raw CLI output if not provided as option
  let rawOutput = options.cliOutput;
  if (!rawOutput) {
    const workdir = options.workdir || path.resolve(repoRoot, 'infra');
    const cliPath = path.resolve(repoRoot, 'node_modules/.bin/supabase');
    const cmd = `"${cliPath}" status --workdir "${workdir}" -o env`;
    try {
      rawOutput = execSync(cmd, { encoding: 'utf8', cwd: repoRoot });
    } catch {
      throw new Error('Local Supabase CLI status query failed.');
    }
  }

  // Parse output & validate loopback constraint
  const parsed = parseSupabaseCliEnv(rawOutput);
  const apiUrl = parsed.API_URL || '';
  if (!apiUrl || !isLoopbackUrl(apiUrl)) {
    throw new Error('Non-loopback Supabase endpoint rejected.');
  }

  // Build content & write file
  const envContent = buildLocalEnvContent(parsed);
  const targetDir = path.dirname(targetPath);
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  fs.writeFileSync(targetPath, envContent, { encoding: 'utf8', mode: 0o600 });

  const keysWritten = [
    'NEXT_PUBLIC_SUPABASE_URL',
    'NEXT_PUBLIC_SUPABASE_ANON_KEY',
    'NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY',
    'SUPABASE_SERVICE_ROLE_KEY',
    'SUPABASE_DRAFT_BUCKET',
    'SUPABASE_PUBLIC_ASSETS_BUCKET',
    'SUPABASE_PUBLIC_FEEDS_BUCKET',
    'SUPABASE_PUBLIC_FEED_FILE',
    'GEMINI_API_KEY',
    'GEMINI_MODEL',
    'GEMINI_ASSISTIVE_EXTRACTION_ENABLED',
  ];

  return { targetPath, keysWritten };
}
