-- Migration 0022: controlled staff identity provisioning.
--
-- Supabase Auth and PostgreSQL are separate systems and cannot share one transaction. This
-- migration therefore uses a durable, fenced execution lease around every external Auth side
-- effect and every database transition.
--
-- Durable lifecycle:
--   reserved            -> one execution owns the right to create the Auth invitation
--   invited             -> an Auth identity carrying this lifecycle's server-controlled marker
--                          is bound to the request
--   pending_activation  -> the staff profile and roles exist, but access remains fail-closed
--   activated           -> the invitee completed account setup and may use their assigned role
--   compensating        -> the current execution exclusively owns destructive Auth cleanup
--   failed              -> the attempt stopped safely; required compensation completed
--   compensation_failed -> cleanup could not complete and the incident remains fail-closed
--
-- The two-minute lease is long enough for one Local/hosted Auth call while still allowing a
-- crashed reserved or invited execution to be recovered promptly. Recovery rotates both the
-- execution token and the one-use Auth ownership marker, fencing every former owner.
--
-- Execution and Auth-ownership credentials are generated by PostgreSQL, returned only to the
-- server-side service and stored here only as SHA-256 hashes. The raw Auth marker is supplied to
-- inviteUserByEmail as transient user metadata. A BEFORE INSERT trigger validates it against the
-- active lease, removes it before persistence, and writes only a one-way lifecycle hash into app
-- metadata. Bind and compensation then require that exact server-controlled marker; Auth
-- creation time is never treated as ownership evidence.
--
-- `bootstrap_initial_admin` is untouched. Every function below is service-role only, except the
-- trigger function (which is executable only by its trigger) and activation, whose input remains
-- the authenticated invitee's exact server-derived Auth identity.

BEGIN;

CREATE TABLE public.staff_provisioning_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  normalized_email text NOT NULL,
  full_name text NOT NULL,
  requested_roles text[] NOT NULL,
  status text NOT NULL DEFAULT 'reserved'
    CONSTRAINT check_staff_provisioning_status CHECK (
      status IN (
        'reserved', 'invited', 'pending_activation', 'activated', 'compensating', 'failed',
        'compensation_failed'
      )
    ),
  requested_by_admin_id uuid REFERENCES public.admin_users(id) ON DELETE SET NULL,
  requested_by_full_name_snapshot text,
  requested_by_email_snapshot text,
  execution_token_hash text NOT NULL
    CONSTRAINT check_staff_provisioning_execution_hash CHECK (
      execution_token_hash ~ '^[0-9a-f]{64}$'
    ),
  auth_ownership_token_hash text NOT NULL
    CONSTRAINT check_staff_provisioning_auth_ownership_hash CHECK (
      auth_ownership_token_hash ~ '^[0-9a-f]{64}$'
    ),
  lease_expires_at timestamptz NOT NULL,
  -- Not a foreign key: compensated Auth identities are deleted while this immutable evidence
  -- intentionally survives.
  auth_user_id uuid,
  -- True only after the exact Auth row is proven to carry this request ID in app metadata.
  auth_identity_owned boolean NOT NULL DEFAULT false,
  admin_user_id uuid REFERENCES public.admin_users(id) ON DELETE SET NULL,
  failure_code text
    CONSTRAINT check_staff_provisioning_failure_code CHECK (
      failure_code IS NULL OR failure_code ~ '^[A-Z][A-Z0-9_]{0,63}$'
    ),
  created_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
  updated_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
  invited_at timestamptz,
  activated_at timestamptz,
  failed_at timestamptz,
  CONSTRAINT check_staff_provisioning_roles CHECK (
    pg_catalog.cardinality(requested_roles) BETWEEN 1 AND 3
    AND pg_catalog.array_position(requested_roles, NULL) IS NULL
    AND requested_roles <@ ARRAY['admin', 'reviewer', 'editor']::text[]
  ),
  CONSTRAINT check_staff_provisioning_ownership_binding CHECK (
    auth_identity_owned = false OR auth_user_id IS NOT NULL
  ),
  CONSTRAINT check_staff_provisioning_terminal_binding CHECK (
    (status = 'reserved' AND auth_user_id IS NULL AND admin_user_id IS NULL)
    OR (status IN ('invited', 'compensating')
      AND auth_user_id IS NOT NULL AND auth_identity_owned = true AND admin_user_id IS NULL)
    OR (status IN ('pending_activation', 'activated')
      AND auth_user_id IS NOT NULL AND auth_identity_owned = true AND admin_user_id IS NOT NULL)
    OR status IN ('failed', 'compensation_failed')
  )
);

CREATE INDEX staff_provisioning_requests_email_idx
  ON public.staff_provisioning_requests(normalized_email);
CREATE INDEX staff_provisioning_requests_admin_user_idx
  ON public.staff_provisioning_requests(admin_user_id);

CREATE UNIQUE INDEX staff_provisioning_requests_active_email_uidx
  ON public.staff_provisioning_requests(normalized_email)
  WHERE status IN ('reserved', 'invited', 'pending_activation', 'activated', 'compensating');

CREATE UNIQUE INDEX staff_provisioning_requests_active_auth_user_uidx
  ON public.staff_provisioning_requests(auth_user_id)
  WHERE auth_user_id IS NOT NULL
    AND status IN ('invited', 'pending_activation', 'activated', 'compensating');

ALTER TABLE public.staff_provisioning_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY admin_all_staff_provisioning_requests ON public.staff_provisioning_requests
  FOR ALL TO authenticated USING (false) WITH CHECK (false);

REVOKE ALL PRIVILEGES ON TABLE public.staff_provisioning_requests
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON TABLE public.staff_provisioning_requests TO service_role;

CREATE OR REPLACE FUNCTION public.canonical_staff_roles(p_roles text[])
RETURNS text[]
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
  SELECT pg_catalog.array_agg(
    r ORDER BY pg_catalog.array_position(ARRAY['admin', 'reviewer', 'editor']::text[], r)
  )
  FROM (
    SELECT DISTINCT pg_catalog.btrim(pg_catalog.lower(x)) AS r
    FROM pg_catalog.unnest(p_roles) x
  ) s;
$$;

REVOKE ALL ON FUNCTION public.canonical_staff_roles(text[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.canonical_staff_roles(text[]) TO service_role;

-- GoTrue maps inviteUserByEmail `data` to raw_user_meta_data. Consume the two internal fields in
-- the same transaction that inserts auth.users, so neither raw credential is ever persisted or
-- returned to the invitee. Any stale/non-owner invitation is aborted before Auth or email exists.
CREATE OR REPLACE FUNCTION public.claim_staff_provisioning_auth_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_request_id uuid;
  v_ownership_token uuid;
  v_request public.staff_provisioning_requests%ROWTYPE;
  v_email text := pg_catalog.lower(pg_catalog.btrim(COALESCE(NEW.email, '')));
BEGIN
  IF NOT (COALESCE(NEW.raw_user_meta_data, '{}'::jsonb) ? 'staff_provisioning_request_id')
     AND NOT (COALESCE(NEW.raw_user_meta_data, '{}'::jsonb) ? 'staff_provisioning_ownership_token')
  THEN
    RETURN NEW;
  END IF;

  IF NOT (COALESCE(NEW.raw_user_meta_data, '{}'::jsonb) ? 'staff_provisioning_request_id')
     OR NOT (COALESCE(NEW.raw_user_meta_data, '{}'::jsonb) ? 'staff_provisioning_ownership_token')
  THEN
    RAISE EXCEPTION 'STAFF_PROVISIONING_INVITE_NOT_OWNED';
  END IF;

  BEGIN
    v_request_id := (NEW.raw_user_meta_data->>'staff_provisioning_request_id')::uuid;
    v_ownership_token := (NEW.raw_user_meta_data->>'staff_provisioning_ownership_token')::uuid;
  EXCEPTION WHEN invalid_text_representation THEN
    RAISE EXCEPTION 'STAFF_PROVISIONING_INVITE_NOT_OWNED';
  END;

  SELECT * INTO v_request
  FROM public.staff_provisioning_requests
  WHERE id = v_request_id
  FOR UPDATE;

  IF NOT FOUND
     OR v_request.status <> 'reserved'
     OR v_request.normalized_email IS DISTINCT FROM v_email
     OR v_request.lease_expires_at <= pg_catalog.now()
     OR v_request.auth_ownership_token_hash IS DISTINCT FROM pg_catalog.encode(
       extensions.digest(pg_catalog.convert_to(v_ownership_token::text, 'UTF8'), 'sha256'),
       'hex'
     )
  THEN
    RAISE EXCEPTION 'STAFF_PROVISIONING_INVITE_NOT_OWNED';
  END IF;

  NEW.raw_user_meta_data := COALESCE(NEW.raw_user_meta_data, '{}'::jsonb)
    - 'staff_provisioning_request_id'
    - 'staff_provisioning_ownership_token';
  NEW.raw_app_meta_data := COALESCE(NEW.raw_app_meta_data, '{}'::jsonb)
    || pg_catalog.jsonb_build_object(
      'staff_provisioning_marker',
      pg_catalog.encode(
        extensions.digest(pg_catalog.convert_to(v_request.id::text, 'UTF8'), 'sha256'), 'hex'
      )
    );
  RETURN NEW;
END;
$$;

CREATE TRIGGER claim_staff_provisioning_auth_insert_before_insert
BEFORE INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.claim_staff_provisioning_auth_insert();

REVOKE ALL ON FUNCTION public.claim_staff_provisioning_auth_insert()
  FROM PUBLIC, anon, authenticated, service_role;

-- Atomically reserve a new lifecycle, observe an active owner, or recover an expired execution.
-- A recovered compensating lifecycle receives a distinct result so callers can resume only cleanup.
CREATE OR REPLACE FUNCTION public.reserve_staff_provisioning(
  p_actor_admin_id uuid,
  p_email text,
  p_full_name text,
  p_roles text[]
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_email text := pg_catalog.lower(pg_catalog.btrim(COALESCE(p_email, '')));
  v_full_name text := pg_catalog.btrim(COALESCE(p_full_name, ''));
  v_roles text[];
  v_actor_full_name text;
  v_actor_email text;
  v_existing public.staff_provisioning_requests%ROWTYPE;
  v_request public.staff_provisioning_requests%ROWTYPE;
  v_execution_token uuid;
  v_auth_ownership_token uuid;
BEGIN
  SELECT full_name, email INTO v_actor_full_name, v_actor_email
  FROM public.admin_users WHERE id = p_actor_admin_id;

  IF NOT FOUND OR NOT EXISTS (
    SELECT 1 FROM public.user_roles WHERE user_id = p_actor_admin_id AND role = 'admin'
  ) THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'PERMISSION_DENIED');
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.staff_provisioning_requests
    WHERE admin_user_id = p_actor_admin_id AND status = 'pending_activation'
  ) THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'PERMISSION_DENIED');
  END IF;

  IF v_email = ''
    OR pg_catalog.length(v_email) > 254
    OR pg_catalog.regexp_match(v_email, '^[^@[:space:]]+@[^@[:space:].]+([.][^@[:space:].]+)+$') IS NULL
    OR v_full_name = ''
    OR pg_catalog.length(v_full_name) > 200
    OR p_roles IS NULL
    OR pg_catalog.cardinality(p_roles) = 0
    OR EXISTS (
      SELECT 1 FROM pg_catalog.unnest(p_roles) x
      WHERE x IS NULL OR pg_catalog.btrim(pg_catalog.lower(x)) NOT IN ('admin', 'reviewer', 'editor')
    )
  THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'VALIDATION_FAILED');
  END IF;

  v_roles := public.canonical_staff_roles(p_roles);
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('capstone.staff_provisioning:' || v_email, 0)
  );

  SELECT * INTO v_existing FROM public.staff_provisioning_requests
  WHERE normalized_email = v_email
    AND status IN (
      'reserved', 'invited', 'pending_activation', 'activated', 'compensating'
    )
  FOR UPDATE;

  IF NOT FOUND AND EXISTS (
    SELECT 1 FROM public.admin_users
    WHERE pg_catalog.lower(pg_catalog.btrim(email)) = v_email
  ) THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'ALREADY_PROVISIONED');
  END IF;

  IF v_existing.id IS NOT NULL THEN
    IF v_existing.status = 'activated' THEN
      RETURN pg_catalog.jsonb_build_object('resultCode', 'ALREADY_PROVISIONED');
    END IF;
    IF v_existing.status = 'pending_activation' THEN
      RETURN pg_catalog.jsonb_build_object('resultCode', 'ALREADY_INVITED');
    END IF;
    IF v_existing.lease_expires_at > pg_catalog.now() THEN
      RETURN pg_catalog.jsonb_build_object('resultCode', 'IN_PROGRESS');
    END IF;

    v_execution_token := gen_random_uuid();
    v_auth_ownership_token := gen_random_uuid();
    UPDATE public.staff_provisioning_requests
       SET execution_token_hash = pg_catalog.encode(
             extensions.digest(pg_catalog.convert_to(v_execution_token::text, 'UTF8'), 'sha256'),
             'hex'
           ),
           auth_ownership_token_hash = pg_catalog.encode(
             extensions.digest(pg_catalog.convert_to(v_auth_ownership_token::text, 'UTF8'), 'sha256'),
             'hex'
           ),
           lease_expires_at = pg_catalog.now() + interval '2 minutes',
           updated_at = pg_catalog.now()
     WHERE id = v_existing.id
     RETURNING * INTO v_existing;

    RETURN pg_catalog.jsonb_build_object(
      'resultCode', CASE WHEN v_existing.status = 'compensating'
        THEN 'RECOVERED_COMPENSATION' ELSE 'RECOVERED' END,
      'requestId', v_existing.id::text,
      'executionToken', v_execution_token::text,
      'authOwnershipToken', v_auth_ownership_token::text,
      'normalizedEmail', v_existing.normalized_email,
      'fullName', v_existing.full_name,
      'roles', pg_catalog.to_jsonb(v_existing.requested_roles),
      'authUserId', v_existing.auth_user_id::text,
      'authIdentityOwned', v_existing.auth_identity_owned,
      'status', v_existing.status
    );
  END IF;

  v_execution_token := gen_random_uuid();
  v_auth_ownership_token := gen_random_uuid();
  INSERT INTO public.staff_provisioning_requests(
    normalized_email, full_name, requested_roles, status,
    requested_by_admin_id, requested_by_full_name_snapshot, requested_by_email_snapshot,
    execution_token_hash, auth_ownership_token_hash, lease_expires_at
  ) VALUES (
    v_email, v_full_name, v_roles, 'reserved',
    p_actor_admin_id, v_actor_full_name, v_actor_email,
    pg_catalog.encode(
      extensions.digest(pg_catalog.convert_to(v_execution_token::text, 'UTF8'), 'sha256'), 'hex'
    ),
    pg_catalog.encode(
      extensions.digest(pg_catalog.convert_to(v_auth_ownership_token::text, 'UTF8'), 'sha256'), 'hex'
    ),
    pg_catalog.now() + interval '2 minutes'
  ) RETURNING * INTO v_request;

  RETURN pg_catalog.jsonb_build_object(
    'resultCode', 'RESERVED',
    'requestId', v_request.id::text,
    'executionToken', v_execution_token::text,
    'authOwnershipToken', v_auth_ownership_token::text,
    'normalizedEmail', v_request.normalized_email,
    'fullName', v_request.full_name,
    'roles', pg_catalog.to_jsonb(v_request.requested_roles),
    'authUserId', NULL,
    'authIdentityOwned', false,
    'status', v_request.status
  );
END;
$$;

REVOKE ALL ON FUNCTION public.reserve_staff_provisioning(uuid, text, text, text[])
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.reserve_staff_provisioning(uuid, text, text, text[])
  TO service_role;

-- Recover an Auth insert whose response was lost or whose owner crashed before bind. Only the
-- exact app-metadata marker is accepted; email and creation time alone are never sufficient.
CREATE OR REPLACE FUNCTION public.recover_staff_provisioning_identity(
  p_request_id uuid,
  p_execution_token uuid
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_request public.staff_provisioning_requests%ROWTYPE;
  v_auth_user_id uuid;
BEGIN
  IF p_request_id IS NULL OR p_execution_token IS NULL THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'VALIDATION_FAILED');
  END IF;

  SELECT * INTO v_request FROM public.staff_provisioning_requests
  WHERE id = p_request_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'REQUEST_NOT_FOUND');
  END IF;
  IF v_request.execution_token_hash IS DISTINCT FROM pg_catalog.encode(
    extensions.digest(pg_catalog.convert_to(p_execution_token::text, 'UTF8'), 'sha256'), 'hex'
  ) THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'EXECUTION_TOKEN_MISMATCH');
  END IF;
  IF v_request.lease_expires_at <= pg_catalog.now() THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'EXECUTION_LEASE_EXPIRED');
  END IF;

  IF v_request.status = 'invited' THEN
    RETURN pg_catalog.jsonb_build_object(
      'resultCode', 'OWNED_IDENTITY_BOUND',
      'authUserId', v_request.auth_user_id::text,
      'authIdentityOwned', v_request.auth_identity_owned
    );
  END IF;
  IF v_request.status <> 'reserved' THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'INVALID_STATE', 'status', v_request.status);
  END IF;

  SELECT id INTO v_auth_user_id
  FROM auth.users
  WHERE pg_catalog.lower(pg_catalog.btrim(email)) = v_request.normalized_email
    AND raw_app_meta_data->>'staff_provisioning_marker' = pg_catalog.encode(
      extensions.digest(pg_catalog.convert_to(v_request.id::text, 'UTF8'), 'sha256'), 'hex'
    )
  LIMIT 1;

  IF v_auth_user_id IS NULL THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'OWNED_IDENTITY_NOT_FOUND');
  END IF;

  UPDATE public.staff_provisioning_requests
     SET auth_user_id = v_auth_user_id,
         auth_identity_owned = true,
         status = 'invited',
         invited_at = COALESCE(invited_at, pg_catalog.now()),
         updated_at = pg_catalog.now(),
         lease_expires_at = pg_catalog.now() + interval '2 minutes'
   WHERE id = v_request.id;

  RETURN pg_catalog.jsonb_build_object(
    'resultCode', 'OWNED_IDENTITY_BOUND',
    'authUserId', v_auth_user_id::text,
    'authIdentityOwned', true
  );
END;
$$;

REVOKE ALL ON FUNCTION public.recover_staff_provisioning_identity(uuid, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.recover_staff_provisioning_identity(uuid, uuid)
  TO service_role;

CREATE OR REPLACE FUNCTION public.bind_staff_provisioning_identity(
  p_request_id uuid,
  p_execution_token uuid,
  p_auth_user_id uuid
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_request public.staff_provisioning_requests%ROWTYPE;
  v_auth_email text;
  v_auth_marker text;
BEGIN
  IF p_request_id IS NULL OR p_execution_token IS NULL OR p_auth_user_id IS NULL THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'VALIDATION_FAILED');
  END IF;

  SELECT * INTO v_request FROM public.staff_provisioning_requests
  WHERE id = p_request_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'REQUEST_NOT_FOUND');
  END IF;
  IF v_request.execution_token_hash IS DISTINCT FROM pg_catalog.encode(
    extensions.digest(pg_catalog.convert_to(p_execution_token::text, 'UTF8'), 'sha256'), 'hex'
  ) THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'EXECUTION_TOKEN_MISMATCH');
  END IF;
  IF v_request.lease_expires_at <= pg_catalog.now() THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'EXECUTION_LEASE_EXPIRED');
  END IF;

  IF v_request.status = 'invited' THEN
    RETURN pg_catalog.jsonb_build_object(
      'resultCode', CASE
        WHEN v_request.auth_user_id = p_auth_user_id THEN 'BOUND'
        ELSE 'ALREADY_BOUND'
      END,
      'authUserId', v_request.auth_user_id::text,
      'authIdentityOwned', v_request.auth_identity_owned
    );
  END IF;
  IF v_request.status <> 'reserved' THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'INVALID_STATE', 'status', v_request.status);
  END IF;

  SELECT pg_catalog.lower(pg_catalog.btrim(email)),
         raw_app_meta_data->>'staff_provisioning_marker'
  INTO v_auth_email, v_auth_marker
  FROM auth.users WHERE id = p_auth_user_id;
  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'AUTH_USER_NOT_FOUND');
  END IF;
  IF v_auth_email IS DISTINCT FROM v_request.normalized_email THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'AUTH_EMAIL_MISMATCH');
  END IF;
  IF v_auth_marker IS DISTINCT FROM pg_catalog.encode(
    extensions.digest(pg_catalog.convert_to(v_request.id::text, 'UTF8'), 'sha256'), 'hex'
  ) THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'AUTH_OWNERSHIP_MISMATCH');
  END IF;

  UPDATE public.staff_provisioning_requests
     SET auth_user_id = p_auth_user_id,
         auth_identity_owned = true,
         status = 'invited',
         invited_at = COALESCE(invited_at, pg_catalog.now()),
         updated_at = pg_catalog.now(),
         lease_expires_at = pg_catalog.now() + interval '2 minutes'
   WHERE id = p_request_id;

  RETURN pg_catalog.jsonb_build_object(
    'resultCode', 'BOUND',
    'authUserId', p_auth_user_id::text,
    'authIdentityOwned', true
  );
END;
$$;

REVOKE ALL ON FUNCTION public.bind_staff_provisioning_identity(uuid, uuid, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.bind_staff_provisioning_identity(uuid, uuid, uuid)
  TO service_role;

CREATE OR REPLACE FUNCTION public.finalize_staff_provisioning(
  p_request_id uuid,
  p_execution_token uuid
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_request public.staff_provisioning_requests%ROWTYPE;
  v_auth_email text;
  v_auth_marker text;
  v_admin_user_id uuid;
  v_existing_auth_user_id uuid;
BEGIN
  IF p_request_id IS NULL OR p_execution_token IS NULL THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'VALIDATION_FAILED');
  END IF;

  SELECT * INTO v_request FROM public.staff_provisioning_requests
  WHERE id = p_request_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'REQUEST_NOT_FOUND');
  END IF;
  IF v_request.execution_token_hash IS DISTINCT FROM pg_catalog.encode(
    extensions.digest(pg_catalog.convert_to(p_execution_token::text, 'UTF8'), 'sha256'), 'hex'
  ) THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'EXECUTION_TOKEN_MISMATCH');
  END IF;
  IF v_request.lease_expires_at <= pg_catalog.now() THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'EXECUTION_LEASE_EXPIRED');
  END IF;
  IF v_request.status <> 'invited'
     OR v_request.auth_user_id IS NULL
     OR v_request.auth_identity_owned = false
  THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'INVALID_STATE', 'status', v_request.status);
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('capstone.staff_provisioning:' || v_request.normalized_email, 0)
  );

  SELECT pg_catalog.lower(pg_catalog.btrim(email)),
         raw_app_meta_data->>'staff_provisioning_marker'
  INTO v_auth_email, v_auth_marker
  FROM auth.users WHERE id = v_request.auth_user_id;
  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'AUTH_USER_NOT_FOUND');
  END IF;
  IF v_auth_email IS DISTINCT FROM v_request.normalized_email THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'AUTH_EMAIL_MISMATCH');
  END IF;
  IF v_auth_marker IS DISTINCT FROM pg_catalog.encode(
    extensions.digest(pg_catalog.convert_to(v_request.id::text, 'UTF8'), 'sha256'), 'hex'
  ) THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'AUTH_OWNERSHIP_MISMATCH');
  END IF;

  SELECT id, auth_user_id INTO v_admin_user_id, v_existing_auth_user_id
  FROM public.admin_users
  WHERE pg_catalog.lower(pg_catalog.btrim(email)) = v_request.normalized_email
     OR auth_user_id = v_request.auth_user_id
  LIMIT 1;

  IF FOUND THEN
    IF v_existing_auth_user_id IS DISTINCT FROM v_request.auth_user_id THEN
      RETURN pg_catalog.jsonb_build_object('resultCode', 'ALREADY_PROVISIONED');
    END IF;
  ELSE
    INSERT INTO public.admin_users(email, full_name, auth_user_id)
    VALUES (v_request.normalized_email, v_request.full_name, v_request.auth_user_id)
    RETURNING id INTO v_admin_user_id;
  END IF;

  INSERT INTO public.user_roles(user_id, role)
  SELECT v_admin_user_id, r FROM pg_catalog.unnest(v_request.requested_roles) r
  ON CONFLICT ON CONSTRAINT unique_user_role DO NOTHING;

  UPDATE public.staff_provisioning_requests
     SET admin_user_id = v_admin_user_id,
         status = 'pending_activation',
         updated_at = pg_catalog.now(),
         lease_expires_at = pg_catalog.now()
   WHERE id = p_request_id;

  RETURN pg_catalog.jsonb_build_object(
    'resultCode', 'SUCCESS',
    'adminUserId', v_admin_user_id::text,
    'status', 'pending_activation'
  );
END;
$$;

REVOKE ALL ON FUNCTION public.finalize_staff_provisioning(uuid, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.finalize_staff_provisioning(uuid, uuid)
  TO service_role;

-- Fence destructive compensation before crossing into Auth. A current recovered owner may repeat
-- this authorization, but only after rechecking the exact server-controlled Auth marker.
CREATE OR REPLACE FUNCTION public.begin_staff_provisioning_compensation(
  p_request_id uuid,
  p_execution_token uuid,
  p_auth_user_id uuid
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_request public.staff_provisioning_requests%ROWTYPE;
  v_auth_marker text;
BEGIN
  IF p_request_id IS NULL OR p_execution_token IS NULL OR p_auth_user_id IS NULL THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'VALIDATION_FAILED');
  END IF;

  SELECT * INTO v_request FROM public.staff_provisioning_requests
  WHERE id = p_request_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'REQUEST_NOT_FOUND');
  END IF;
  IF v_request.execution_token_hash IS DISTINCT FROM pg_catalog.encode(
    extensions.digest(pg_catalog.convert_to(p_execution_token::text, 'UTF8'), 'sha256'), 'hex'
  ) THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'EXECUTION_TOKEN_MISMATCH');
  END IF;
  IF v_request.lease_expires_at <= pg_catalog.now() THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'EXECUTION_LEASE_EXPIRED');
  END IF;
  IF v_request.status NOT IN ('invited', 'compensating')
     OR v_request.auth_user_id IS DISTINCT FROM p_auth_user_id
     OR v_request.auth_identity_owned = false
  THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'COMPENSATION_NOT_AUTHORIZED');
  END IF;

  SELECT raw_app_meta_data->>'staff_provisioning_marker' INTO v_auth_marker
  FROM auth.users WHERE id = p_auth_user_id;
  IF NOT FOUND THEN
    IF v_request.status = 'compensating' THEN
      RETURN pg_catalog.jsonb_build_object('resultCode', 'COMPENSATION_ALREADY_COMPLETE');
    END IF;
    RETURN pg_catalog.jsonb_build_object('resultCode', 'COMPENSATION_NOT_AUTHORIZED');
  END IF;
  IF v_auth_marker IS DISTINCT FROM pg_catalog.encode(
    extensions.digest(pg_catalog.convert_to(v_request.id::text, 'UTF8'), 'sha256'), 'hex'
  ) THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'COMPENSATION_NOT_AUTHORIZED');
  END IF;

  UPDATE public.staff_provisioning_requests
     SET status = 'compensating',
         updated_at = pg_catalog.now(),
         lease_expires_at = pg_catalog.now() + interval '2 minutes'
   WHERE id = p_request_id;

  RETURN pg_catalog.jsonb_build_object('resultCode', 'COMPENSATION_AUTHORIZED');
END;
$$;

REVOKE ALL ON FUNCTION public.begin_staff_provisioning_compensation(uuid, uuid, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.begin_staff_provisioning_compensation(uuid, uuid, uuid)
  TO service_role;

-- Activation deliberately needs no provisioning execution token. It remains bound solely to the
-- exact authenticated invitee identity and works even when new invitation creation is disabled.
CREATE OR REPLACE FUNCTION public.activate_staff_provisioning(p_auth_user_id uuid)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_request public.staff_provisioning_requests%ROWTYPE;
  v_profile_auth_user_id uuid;
BEGIN
  IF p_auth_user_id IS NULL THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'ACTIVATION_MISMATCH');
  END IF;

  SELECT * INTO v_request FROM public.staff_provisioning_requests
  WHERE auth_user_id = p_auth_user_id
    AND status IN ('pending_activation', 'activated')
  FOR UPDATE;
  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'ACTIVATION_MISMATCH');
  END IF;
  IF v_request.status = 'activated' THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'ALREADY_ACTIVATED');
  END IF;

  SELECT auth_user_id INTO v_profile_auth_user_id
  FROM public.admin_users WHERE id = v_request.admin_user_id;
  IF NOT FOUND OR v_profile_auth_user_id IS DISTINCT FROM p_auth_user_id THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'ACTIVATION_MISMATCH');
  END IF;

  UPDATE public.staff_provisioning_requests
     SET status = 'activated', activated_at = pg_catalog.now(), updated_at = pg_catalog.now()
   WHERE id = v_request.id;
  RETURN pg_catalog.jsonb_build_object('resultCode', 'ACTIVATED');
END;
$$;

REVOKE ALL ON FUNCTION public.activate_staff_provisioning(uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.activate_staff_provisioning(uuid) TO service_role;

CREATE OR REPLACE FUNCTION public.fail_staff_provisioning(
  p_request_id uuid,
  p_execution_token uuid,
  p_failure_code text,
  p_compensation_state text
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_request public.staff_provisioning_requests%ROWTYPE;
  v_status text;
BEGIN
  IF p_request_id IS NULL
    OR p_execution_token IS NULL
    OR p_compensation_state IS NULL
    OR p_compensation_state NOT IN ('not_required', 'succeeded', 'failed')
    OR p_failure_code IS NULL
    OR pg_catalog.regexp_match(p_failure_code, '^[A-Z][A-Z0-9_]{0,63}$') IS NULL
  THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'VALIDATION_FAILED');
  END IF;

  SELECT * INTO v_request FROM public.staff_provisioning_requests
  WHERE id = p_request_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'REQUEST_NOT_FOUND');
  END IF;
  IF v_request.execution_token_hash IS DISTINCT FROM pg_catalog.encode(
    extensions.digest(pg_catalog.convert_to(p_execution_token::text, 'UTF8'), 'sha256'), 'hex'
  ) THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'EXECUTION_TOKEN_MISMATCH');
  END IF;
  IF v_request.lease_expires_at <= pg_catalog.now() THEN
    RETURN pg_catalog.jsonb_build_object('resultCode', 'EXECUTION_LEASE_EXPIRED');
  END IF;

  IF p_compensation_state = 'not_required' THEN
    IF v_request.status <> 'reserved'
       OR v_request.auth_user_id IS NOT NULL
       OR v_request.auth_identity_owned = true
    THEN
      RETURN pg_catalog.jsonb_build_object('resultCode', 'COMPENSATION_NOT_AUTHORIZED');
    END IF;
  ELSE
    IF v_request.status <> 'compensating'
       OR v_request.auth_user_id IS NULL
       OR v_request.auth_identity_owned = false
    THEN
      RETURN pg_catalog.jsonb_build_object('resultCode', 'COMPENSATION_NOT_AUTHORIZED');
    END IF;
    IF p_compensation_state = 'succeeded' AND EXISTS (
      SELECT 1 FROM auth.users WHERE id = v_request.auth_user_id
    ) THEN
      RETURN pg_catalog.jsonb_build_object('resultCode', 'COMPENSATION_NOT_CONFIRMED');
    END IF;
  END IF;

  v_status := CASE WHEN p_compensation_state = 'failed'
    THEN 'compensation_failed' ELSE 'failed' END;

  UPDATE public.staff_provisioning_requests
     SET status = v_status,
         failure_code = p_failure_code,
         failed_at = pg_catalog.now(),
         updated_at = pg_catalog.now(),
         lease_expires_at = pg_catalog.now()
   WHERE id = p_request_id;

  RETURN pg_catalog.jsonb_build_object(
    'resultCode', CASE WHEN v_status = 'failed' THEN 'FAILED' ELSE 'COMPENSATION_FAILED' END,
    'authUserId', v_request.auth_user_id::text,
    'authIdentityOwned', v_request.auth_identity_owned
  );
END;
$$;

REVOKE ALL ON FUNCTION public.fail_staff_provisioning(uuid, uuid, text, text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fail_staff_provisioning(uuid, uuid, text, text)
  TO service_role;

COMMIT;
